// Code generated by internal/cmd/generate from clay.h; DO NOT EDIT.

package clay

type PointerDataInteractionState uint8

const (
	POINTER_DATA_PRESSED_THIS_FRAME  PointerDataInteractionState = 0
	POINTER_DATA_PRESSED             PointerDataInteractionState = 1
	POINTER_DATA_RELEASED_THIS_FRAME PointerDataInteractionState = 2
	POINTER_DATA_RELEASED            PointerDataInteractionState = 3
)

type RenderCommandType uint8

const (
	RENDER_COMMAND_TYPE_NONE                RenderCommandType = 0
	RENDER_COMMAND_TYPE_RECTANGLE           RenderCommandType = 1
	RENDER_COMMAND_TYPE_BORDER              RenderCommandType = 2
	RENDER_COMMAND_TYPE_TEXT                RenderCommandType = 3
	RENDER_COMMAND_TYPE_IMAGE               RenderCommandType = 4
	RENDER_COMMAND_TYPE_SCISSOR_START       RenderCommandType = 5
	RENDER_COMMAND_TYPE_SCISSOR_END         RenderCommandType = 6
	RENDER_COMMAND_TYPE_OVERLAY_COLOR_START RenderCommandType = 7
	RENDER_COMMAND_TYPE_OVERLAY_COLOR_END   RenderCommandType = 8
	RENDER_COMMAND_TYPE_CUSTOM              RenderCommandType = 9
)

type TransitionState int32

const (
	TRANSITION_STATE_IDLE          TransitionState = 0
	TRANSITION_STATE_ENTERING      TransitionState = 1
	TRANSITION_STATE_TRANSITIONING TransitionState = 2
	TRANSITION_STATE_EXITING       TransitionState = 3
)

type TransitionProperty int32

const (
	TRANSITION_PROPERTY_NONE             TransitionProperty = 0
	TRANSITION_PROPERTY_X                TransitionProperty = 1
	TRANSITION_PROPERTY_Y                TransitionProperty = 2
	TRANSITION_PROPERTY_POSITION         TransitionProperty = 3
	TRANSITION_PROPERTY_WIDTH            TransitionProperty = 4
	TRANSITION_PROPERTY_HEIGHT           TransitionProperty = 8
	TRANSITION_PROPERTY_DIMENSIONS       TransitionProperty = 12
	TRANSITION_PROPERTY_BOUNDING_BOX     TransitionProperty = 15
	TRANSITION_PROPERTY_BACKGROUND_COLOR TransitionProperty = 16
	TRANSITION_PROPERTY_OVERLAY_COLOR    TransitionProperty = 32
	TRANSITION_PROPERTY_CORNER_RADIUS    TransitionProperty = 64
	TRANSITION_PROPERTY_BORDER_COLOR     TransitionProperty = 128
	TRANSITION_PROPERTY_BORDER_WIDTH     TransitionProperty = 256
	TRANSITION_PROPERTY_BORDER           TransitionProperty = 384
)

type __SizingType uint8

const (
	__SIZING_TYPE_FIT     __SizingType = 0
	__SIZING_TYPE_GROW    __SizingType = 1
	__SIZING_TYPE_PERCENT __SizingType = 2
	__SIZING_TYPE_FIXED   __SizingType = 3
)

type LayoutAlignmentX uint8

const (
	ALIGN_X_LEFT   LayoutAlignmentX = 0
	ALIGN_X_RIGHT  LayoutAlignmentX = 1
	ALIGN_X_CENTER LayoutAlignmentX = 2
)

type LayoutAlignmentY uint8

const (
	ALIGN_Y_TOP    LayoutAlignmentY = 0
	ALIGN_Y_BOTTOM LayoutAlignmentY = 1
	ALIGN_Y_CENTER LayoutAlignmentY = 2
)

type LayoutDirection uint8

const (
	LEFT_TO_RIGHT LayoutDirection = 0
	TOP_TO_BOTTOM LayoutDirection = 1
)

type FloatingAttachPointType uint8

const (
	ATTACH_POINT_LEFT_TOP      FloatingAttachPointType = 0
	ATTACH_POINT_LEFT_CENTER   FloatingAttachPointType = 1
	ATTACH_POINT_LEFT_BOTTOM   FloatingAttachPointType = 2
	ATTACH_POINT_CENTER_TOP    FloatingAttachPointType = 3
	ATTACH_POINT_CENTER_CENTER FloatingAttachPointType = 4
	ATTACH_POINT_CENTER_BOTTOM FloatingAttachPointType = 5
	ATTACH_POINT_RIGHT_TOP     FloatingAttachPointType = 6
	ATTACH_POINT_RIGHT_CENTER  FloatingAttachPointType = 7
	ATTACH_POINT_RIGHT_BOTTOM  FloatingAttachPointType = 8
)

type PointerCaptureMode uint8

const (
	POINTER_CAPTURE_MODE_CAPTURE     PointerCaptureMode = 0
	POINTER_CAPTURE_MODE_PASSTHROUGH PointerCaptureMode = 1
)

type FloatingAttachToElement uint8

const (
	ATTACH_TO_NONE            FloatingAttachToElement = 0
	ATTACH_TO_PARENT          FloatingAttachToElement = 1
	ATTACH_TO_ELEMENT_WITH_ID FloatingAttachToElement = 2
	ATTACH_TO_ROOT            FloatingAttachToElement = 3
)

type FloatingClipToElement uint8

const (
	CLIP_TO_NONE            FloatingClipToElement = 0
	CLIP_TO_ATTACHED_PARENT FloatingClipToElement = 1
)

type TransitionInteractionHandlingType uint8

const (
	TRANSITION_DISABLE_INTERACTIONS_WHILE_TRANSITIONING_POSITION TransitionInteractionHandlingType = 0
	TRANSITION_ALLOW_INTERACTIONS_WHILE_TRANSITIONING_POSITION   TransitionInteractionHandlingType = 1
)

type TransitionEnterTriggerType uint8

const (
	TRANSITION_ENTER_SKIP_ON_FIRST_PARENT_FRAME    TransitionEnterTriggerType = 0
	TRANSITION_ENTER_TRIGGER_ON_FIRST_PARENT_FRAME TransitionEnterTriggerType = 1
)

type TransitionExitTriggerType uint8

const (
	TRANSITION_EXIT_SKIP_WHEN_PARENT_EXITS    TransitionExitTriggerType = 0
	TRANSITION_EXIT_TRIGGER_WHEN_PARENT_EXITS TransitionExitTriggerType = 1
)

type ExitTransitionSiblingOrdering uint8

const (
	EXIT_TRANSITION_ORDERING_UNDERNEATH_SIBLINGS ExitTransitionSiblingOrdering = 0
	EXIT_TRANSITION_ORDERING_NATURAL_ORDER       ExitTransitionSiblingOrdering = 1
	EXIT_TRANSITION_ORDERING_ABOVE_SIBLINGS      ExitTransitionSiblingOrdering = 2
)

type TextElementConfigWrapMode uint8

const (
	TEXT_WRAP_WORDS    TextElementConfigWrapMode = 0
	TEXT_WRAP_NEWLINES TextElementConfigWrapMode = 1
	TEXT_WRAP_NONE     TextElementConfigWrapMode = 2
)

type TextAlignment uint8

const (
	TEXT_ALIGN_LEFT   TextAlignment = 0
	TEXT_ALIGN_CENTER TextAlignment = 1
	TEXT_ALIGN_RIGHT  TextAlignment = 2
)

type ErrorType uint8

const (
	ERROR_TYPE_TEXT_MEASUREMENT_FUNCTION_NOT_PROVIDED ErrorType = 0
	ERROR_TYPE_ARENA_CAPACITY_EXCEEDED                ErrorType = 1
	ERROR_TYPE_ELEMENTS_CAPACITY_EXCEEDED             ErrorType = 2
	ERROR_TYPE_TEXT_MEASUREMENT_CAPACITY_EXCEEDED     ErrorType = 3
	ERROR_TYPE_DUPLICATE_ID                           ErrorType = 4
	ERROR_TYPE_FLOATING_CONTAINER_PARENT_NOT_FOUND    ErrorType = 5
	ERROR_TYPE_PERCENTAGE_OVER_1                      ErrorType = 6
	ERROR_TYPE_INTERNAL_ERROR                         ErrorType = 7
	ERROR_TYPE_UNBALANCED_OPEN_CLOSE                  ErrorType = 8
	ERROR_TYPE_HASH_MAP_CAPACITY_EXCEEDED             ErrorType = 9
)

type Vector2 struct {
	X float32
	Y float32
}

const sizeofVector2 = 8

func encVector2(b []byte, p uint32, v *Vector2) {
	putF32(b, p+0, v.X)
	putF32(b, p+4, v.Y)
}

func decVector2(m []byte, p uint32, v *Vector2) {
	v.X = getF32(m, p+0)
	v.Y = getF32(m, p+4)
}

type PointerData struct {
	Position Vector2
	State    PointerDataInteractionState
}

const sizeofPointerData = 12

func encPointerData(b []byte, p uint32, v *PointerData) {
	encVector2(b, p+0, &v.Position)
	putU8(b, p+8, uint8(v.State))
}

func decPointerData(m []byte, p uint32, v *PointerData) {
	decVector2(m, p+0, &v.Position)
	v.State = PointerDataInteractionState(getU8(m, p+8))
}

type Dimensions struct {
	Width  float32
	Height float32
}

const sizeofDimensions = 8

func encDimensions(b []byte, p uint32, v *Dimensions) {
	putF32(b, p+0, v.Width)
	putF32(b, p+4, v.Height)
}

func decDimensions(m []byte, p uint32, v *Dimensions) {
	v.Width = getF32(m, p+0)
	v.Height = getF32(m, p+4)
}

type BoundingBox struct {
	X      float32
	Y      float32
	Width  float32
	Height float32
}

const sizeofBoundingBox = 16

func encBoundingBox(b []byte, p uint32, v *BoundingBox) {
	putF32(b, p+0, v.X)
	putF32(b, p+4, v.Y)
	putF32(b, p+8, v.Width)
	putF32(b, p+12, v.Height)
}

func decBoundingBox(m []byte, p uint32, v *BoundingBox) {
	v.X = getF32(m, p+0)
	v.Y = getF32(m, p+4)
	v.Width = getF32(m, p+8)
	v.Height = getF32(m, p+12)
}

type Color struct {
	R float32
	G float32
	B float32
	A float32
}

const sizeofColor = 16

func encColor(b []byte, p uint32, v *Color) {
	putF32(b, p+0, v.R)
	putF32(b, p+4, v.G)
	putF32(b, p+8, v.B)
	putF32(b, p+12, v.A)
}

func decColor(m []byte, p uint32, v *Color) {
	v.R = getF32(m, p+0)
	v.G = getF32(m, p+4)
	v.B = getF32(m, p+8)
	v.A = getF32(m, p+12)
}

type CornerRadius struct {
	TopLeft     float32
	TopRight    float32
	BottomLeft  float32
	BottomRight float32
}

const sizeofCornerRadius = 16

func encCornerRadius(b []byte, p uint32, v *CornerRadius) {
	putF32(b, p+0, v.TopLeft)
	putF32(b, p+4, v.TopRight)
	putF32(b, p+8, v.BottomLeft)
	putF32(b, p+12, v.BottomRight)
}

func decCornerRadius(m []byte, p uint32, v *CornerRadius) {
	v.TopLeft = getF32(m, p+0)
	v.TopRight = getF32(m, p+4)
	v.BottomLeft = getF32(m, p+8)
	v.BottomRight = getF32(m, p+12)
}

type RectangleRenderData struct {
	BackgroundColor Color
	CornerRadius    CornerRadius
}

const sizeofRectangleRenderData = 32

func encRectangleRenderData(b []byte, p uint32, v *RectangleRenderData) {
	encColor(b, p+0, &v.BackgroundColor)
	encCornerRadius(b, p+16, &v.CornerRadius)
}

func decRectangleRenderData(m []byte, p uint32, v *RectangleRenderData) {
	decColor(m, p+0, &v.BackgroundColor)
	decCornerRadius(m, p+16, &v.CornerRadius)
}

const sizeofStringSlice = 12

func encStringSlice(b []byte, p uint32, v *string) {
	addr := storeString(*v)
	putU32(b, p+4, addr)
	putU32(b, p+0, uint32(len(*v)))
	putU32(b, p+8, addr)
}

func decStringSlice(m []byte, p uint32, v *string) {
	*v = loadString(m, getU32(m, p+4), getU32(m, p+0))
}

type TextRenderData struct {
	StringContents string
	TextColor      Color
	FontId         uint16
	FontSize       uint16
	LetterSpacing  uint16
	LineHeight     uint16
}

const sizeofTextRenderData = 36

func encTextRenderData(b []byte, p uint32, v *TextRenderData) {
	encStringSlice(b, p+0, &v.StringContents)
	encColor(b, p+12, &v.TextColor)
	putU16(b, p+28, uint16(v.FontId))
	putU16(b, p+30, uint16(v.FontSize))
	putU16(b, p+32, uint16(v.LetterSpacing))
	putU16(b, p+34, uint16(v.LineHeight))
}

func decTextRenderData(m []byte, p uint32, v *TextRenderData) {
	decStringSlice(m, p+0, &v.StringContents)
	decColor(m, p+12, &v.TextColor)
	v.FontId = uint16(getU16(m, p+28))
	v.FontSize = uint16(getU16(m, p+30))
	v.LetterSpacing = uint16(getU16(m, p+32))
	v.LineHeight = uint16(getU16(m, p+34))
}

type ImageRenderData struct {
	BackgroundColor Color
	CornerRadius    CornerRadius
	ImageData       any
}

const sizeofImageRenderData = 36

func encImageRenderData(b []byte, p uint32, v *ImageRenderData) {
	encColor(b, p+0, &v.BackgroundColor)
	encCornerRadius(b, p+16, &v.CornerRadius)
	putU32(b, p+32, storeHandle(v.ImageData))
}

func decImageRenderData(m []byte, p uint32, v *ImageRenderData) {
	decColor(m, p+0, &v.BackgroundColor)
	decCornerRadius(m, p+16, &v.CornerRadius)
	v.ImageData = loadHandle(getU32(m, p+32))
}

type CustomRenderData struct {
	BackgroundColor Color
	CornerRadius    CornerRadius
	CustomData      any
}

const sizeofCustomRenderData = 36

func encCustomRenderData(b []byte, p uint32, v *CustomRenderData) {
	encColor(b, p+0, &v.BackgroundColor)
	encCornerRadius(b, p+16, &v.CornerRadius)
	putU32(b, p+32, storeHandle(v.CustomData))
}

func decCustomRenderData(m []byte, p uint32, v *CustomRenderData) {
	decColor(m, p+0, &v.BackgroundColor)
	decCornerRadius(m, p+16, &v.CornerRadius)
	v.CustomData = loadHandle(getU32(m, p+32))
}

type BorderWidth struct {
	Left            uint16
	Right           uint16
	Top             uint16
	Bottom          uint16
	BetweenChildren uint16
}

const sizeofBorderWidth = 10

func encBorderWidth(b []byte, p uint32, v *BorderWidth) {
	putU16(b, p+0, uint16(v.Left))
	putU16(b, p+2, uint16(v.Right))
	putU16(b, p+4, uint16(v.Top))
	putU16(b, p+6, uint16(v.Bottom))
	putU16(b, p+8, uint16(v.BetweenChildren))
}

func decBorderWidth(m []byte, p uint32, v *BorderWidth) {
	v.Left = uint16(getU16(m, p+0))
	v.Right = uint16(getU16(m, p+2))
	v.Top = uint16(getU16(m, p+4))
	v.Bottom = uint16(getU16(m, p+6))
	v.BetweenChildren = uint16(getU16(m, p+8))
}

type BorderRenderData struct {
	Color        Color
	CornerRadius CornerRadius
	Width        BorderWidth
}

const sizeofBorderRenderData = 44

func encBorderRenderData(b []byte, p uint32, v *BorderRenderData) {
	encColor(b, p+0, &v.Color)
	encCornerRadius(b, p+16, &v.CornerRadius)
	encBorderWidth(b, p+32, &v.Width)
}

func decBorderRenderData(m []byte, p uint32, v *BorderRenderData) {
	decColor(m, p+0, &v.Color)
	decCornerRadius(m, p+16, &v.CornerRadius)
	decBorderWidth(m, p+32, &v.Width)
}

type ClipRenderData struct {
	Horizontal bool
	Vertical   bool
}

const sizeofClipRenderData = 2

func encClipRenderData(b []byte, p uint32, v *ClipRenderData) {
	putBool(b, p+0, v.Horizontal)
	putBool(b, p+1, v.Vertical)
}

func decClipRenderData(m []byte, p uint32, v *ClipRenderData) {
	v.Horizontal = getBool(m, p+0)
	v.Vertical = getBool(m, p+1)
}

type OverlayColorRenderData struct {
	Color Color
}

const sizeofOverlayColorRenderData = 16

func encOverlayColorRenderData(b []byte, p uint32, v *OverlayColorRenderData) {
	encColor(b, p+0, &v.Color)
}

func decOverlayColorRenderData(m []byte, p uint32, v *OverlayColorRenderData) {
	decColor(m, p+0, &v.Color)
}

type RenderData struct {
	// union
	Rectangle    RectangleRenderData
	Text         TextRenderData
	Image        ImageRenderData
	Custom       CustomRenderData
	Border       BorderRenderData
	Clip         ClipRenderData
	OverlayColor OverlayColorRenderData
}

const sizeofRenderData = 44

type RenderCommand struct {
	BoundingBox BoundingBox
	RenderData  RenderData
	UserData    any
	Id          uint32
	ZIndex      int16
	CommandType RenderCommandType
}

const sizeofRenderCommand = 72

func decRenderCommand(m []byte, p uint32, v *RenderCommand) {
	decBoundingBox(m, p+0, &v.BoundingBox)
	v.UserData = loadHandle(getU32(m, p+60))
	v.Id = uint32(getU32(m, p+64))
	v.ZIndex = int16(getU16(m, p+68))
	v.CommandType = RenderCommandType(getU8(m, p+70))
	v.RenderData = RenderData{}
	switch v.CommandType {
	case RENDER_COMMAND_TYPE_RECTANGLE:
		decRectangleRenderData(m, p+16+0, &v.RenderData.Rectangle)
	case RENDER_COMMAND_TYPE_BORDER:
		decBorderRenderData(m, p+16+0, &v.RenderData.Border)
	case RENDER_COMMAND_TYPE_TEXT:
		decTextRenderData(m, p+16+0, &v.RenderData.Text)
	case RENDER_COMMAND_TYPE_IMAGE:
		decImageRenderData(m, p+16+0, &v.RenderData.Image)
	case RENDER_COMMAND_TYPE_SCISSOR_START:
		decClipRenderData(m, p+16+0, &v.RenderData.Clip)
	case RENDER_COMMAND_TYPE_SCISSOR_END:
		decClipRenderData(m, p+16+0, &v.RenderData.Clip)
	case RENDER_COMMAND_TYPE_OVERLAY_COLOR_START:
		decOverlayColorRenderData(m, p+16+0, &v.RenderData.OverlayColor)
	case RENDER_COMMAND_TYPE_OVERLAY_COLOR_END:
		decOverlayColorRenderData(m, p+16+0, &v.RenderData.OverlayColor)
	case RENDER_COMMAND_TYPE_CUSTOM:
		decCustomRenderData(m, p+16+0, &v.RenderData.Custom)
	}
}

type RenderCommandArray []RenderCommand

const sizeofRenderCommandArray = 12

func decRenderCommandArray(m []byte, p uint32, v *RenderCommandArray) {
	n := int(int32(getU32(m, p+4)))
	addr := getU32(m, p+8)
	s := (*v)[:0]
	if n <= 0 {
		*v = s
		return
	}
	if cap(s) < n {
		s = make(RenderCommandArray, n)
	}
	s = s[:n]
	for i := range s {
		decRenderCommand(m, addr+uint32(i)*72, &s[i])
	}
	*v = s
}

const sizeofString = 12

func encString(b []byte, p uint32, v *string) {
	addr := storeString(*v)
	putU32(b, p+8, addr)
	putU32(b, p+4, uint32(len(*v)))
}

func decString(m []byte, p uint32, v *string) {
	*v = loadString(m, getU32(m, p+8), getU32(m, p+4))
}

type ElementId struct {
	Id       uint32
	Offset   uint32
	BaseId   uint32
	StringId string
}

const sizeofElementId = 24

func encElementId(b []byte, p uint32, v *ElementId) {
	putU32(b, p+0, uint32(v.Id))
	putU32(b, p+4, uint32(v.Offset))
	putU32(b, p+8, uint32(v.BaseId))
	encString(b, p+12, &v.StringId)
}

func decElementId(m []byte, p uint32, v *ElementId) {
	v.Id = uint32(getU32(m, p+0))
	v.Offset = uint32(getU32(m, p+4))
	v.BaseId = uint32(getU32(m, p+8))
	decString(m, p+12, &v.StringId)
}

type ElementData struct {
	BoundingBox BoundingBox
	Found       bool
}

const sizeofElementData = 20

func encElementData(b []byte, p uint32, v *ElementData) {
	encBoundingBox(b, p+0, &v.BoundingBox)
	putBool(b, p+16, v.Found)
}

func decElementData(m []byte, p uint32, v *ElementData) {
	decBoundingBox(m, p+0, &v.BoundingBox)
	v.Found = getBool(m, p+16)
}

type ElementIdArray []ElementId

const sizeofElementIdArray = 12

func decElementIdArray(m []byte, p uint32, v *ElementIdArray) {
	n := int(int32(getU32(m, p+4)))
	addr := getU32(m, p+8)
	s := (*v)[:0]
	if n <= 0 {
		*v = s
		return
	}
	if cap(s) < n {
		s = make(ElementIdArray, n)
	}
	s = s[:n]
	for i := range s {
		decElementId(m, addr+uint32(i)*24, &s[i])
	}
	*v = s
}

type ClipElementConfig struct {
	Horizontal  bool
	Vertical    bool
	ChildOffset Vector2
}

const sizeofClipElementConfig = 12

func encClipElementConfig(b []byte, p uint32, v *ClipElementConfig) {
	putBool(b, p+0, v.Horizontal)
	putBool(b, p+1, v.Vertical)
	encVector2(b, p+4, &v.ChildOffset)
}

func decClipElementConfig(m []byte, p uint32, v *ClipElementConfig) {
	v.Horizontal = getBool(m, p+0)
	v.Vertical = getBool(m, p+1)
	decVector2(m, p+4, &v.ChildOffset)
}

type ScrollContainerData struct {
	ScrollPosition            Pointer[Vector2]
	ScrollContainerDimensions Dimensions
	ContentDimensions         Dimensions
	Config                    ClipElementConfig
	Found                     bool
}

const sizeofScrollContainerData = 36

func decScrollContainerData(m []byte, p uint32, v *ScrollContainerData) {
	v.ScrollPosition = Pointer[Vector2]{addr: getU32(m, p+0)}
	decDimensions(m, p+4, &v.ScrollContainerDimensions)
	decDimensions(m, p+12, &v.ContentDimensions)
	decClipElementConfig(m, p+20, &v.Config)
	v.Found = getBool(m, p+32)
}

type TransitionData struct {
	BoundingBox     BoundingBox
	BackgroundColor Color
	OverlayColor    Color
	BorderColor     Color
	BorderWidth     BorderWidth
}

const sizeofTransitionData = 76

func encTransitionData(b []byte, p uint32, v *TransitionData) {
	encBoundingBox(b, p+0, &v.BoundingBox)
	encColor(b, p+16, &v.BackgroundColor)
	encColor(b, p+32, &v.OverlayColor)
	encColor(b, p+48, &v.BorderColor)
	encBorderWidth(b, p+64, &v.BorderWidth)
}

func decTransitionData(m []byte, p uint32, v *TransitionData) {
	decBoundingBox(m, p+0, &v.BoundingBox)
	decColor(m, p+16, &v.BackgroundColor)
	decColor(m, p+32, &v.OverlayColor)
	decColor(m, p+48, &v.BorderColor)
	decBorderWidth(m, p+64, &v.BorderWidth)
}

type TransitionCallbackArguments struct {
	TransitionState TransitionState
	Initial         TransitionData
	Current         Pointer[TransitionData]
	Target          TransitionData
	ElapsedTime     float32
	Duration        float32
	Properties      TransitionProperty
}

const sizeofTransitionCallbackArguments = 172

func decTransitionCallbackArguments(m []byte, p uint32, v *TransitionCallbackArguments) {
	v.TransitionState = TransitionState(getU32(m, p+0))
	decTransitionData(m, p+4, &v.Initial)
	v.Current = Pointer[TransitionData]{addr: getU32(m, p+80)}
	decTransitionData(m, p+84, &v.Target)
	v.ElapsedTime = getF32(m, p+160)
	v.Duration = getF32(m, p+164)
	v.Properties = TransitionProperty(getU32(m, p+168))
}

type SizingMinMax struct {
	Min float32
	Max float32
}

const sizeofSizingMinMax = 8

func encSizingMinMax(b []byte, p uint32, v *SizingMinMax) {
	putF32(b, p+0, v.Min)
	putF32(b, p+4, v.Max)
}

func decSizingMinMax(m []byte, p uint32, v *SizingMinMax) {
	v.Min = getF32(m, p+0)
	v.Max = getF32(m, p+4)
}

type SizingAxis struct {
	Size struct {
		// union
		MinMax  SizingMinMax
		Percent float32
	}
	Type __SizingType
}

const sizeofSizingAxis = 12

func encSizingAxis(b []byte, p uint32, v *SizingAxis) {
	switch {
	case v.Size.MinMax != (SizingMinMax{}):
		encSizingMinMax(b, p+0+0, &v.Size.MinMax)
	case v.Size.Percent != 0:
		putF32(b, p+0+0, v.Size.Percent)
	}

	putU8(b, p+8, uint8(v.Type))
}

func decSizingAxis(m []byte, p uint32, v *SizingAxis) {
	decSizingMinMax(m, p+0+0, &v.Size.MinMax)
	v.Size.Percent = getF32(m, p+0+0)

	v.Type = __SizingType(getU8(m, p+8))
}

type Sizing struct {
	Width  SizingAxis
	Height SizingAxis
}

const sizeofSizing = 24

func encSizing(b []byte, p uint32, v *Sizing) {
	encSizingAxis(b, p+0, &v.Width)
	encSizingAxis(b, p+12, &v.Height)
}

func decSizing(m []byte, p uint32, v *Sizing) {
	decSizingAxis(m, p+0, &v.Width)
	decSizingAxis(m, p+12, &v.Height)
}

type Padding struct {
	Left   uint16
	Right  uint16
	Top    uint16
	Bottom uint16
}

const sizeofPadding = 8

func encPadding(b []byte, p uint32, v *Padding) {
	putU16(b, p+0, uint16(v.Left))
	putU16(b, p+2, uint16(v.Right))
	putU16(b, p+4, uint16(v.Top))
	putU16(b, p+6, uint16(v.Bottom))
}

func decPadding(m []byte, p uint32, v *Padding) {
	v.Left = uint16(getU16(m, p+0))
	v.Right = uint16(getU16(m, p+2))
	v.Top = uint16(getU16(m, p+4))
	v.Bottom = uint16(getU16(m, p+6))
}

type ChildAlignment struct {
	X LayoutAlignmentX
	Y LayoutAlignmentY
}

const sizeofChildAlignment = 2

func encChildAlignment(b []byte, p uint32, v *ChildAlignment) {
	putU8(b, p+0, uint8(v.X))
	putU8(b, p+1, uint8(v.Y))
}

func decChildAlignment(m []byte, p uint32, v *ChildAlignment) {
	v.X = LayoutAlignmentX(getU8(m, p+0))
	v.Y = LayoutAlignmentY(getU8(m, p+1))
}

type LayoutConfig struct {
	Sizing          Sizing
	Padding         Padding
	ChildGap        uint16
	ChildAlignment  ChildAlignment
	LayoutDirection LayoutDirection
}

const sizeofLayoutConfig = 40

func encLayoutConfig(b []byte, p uint32, v *LayoutConfig) {
	encSizing(b, p+0, &v.Sizing)
	encPadding(b, p+24, &v.Padding)
	putU16(b, p+32, uint16(v.ChildGap))
	encChildAlignment(b, p+34, &v.ChildAlignment)
	putU8(b, p+36, uint8(v.LayoutDirection))
}

func decLayoutConfig(m []byte, p uint32, v *LayoutConfig) {
	decSizing(m, p+0, &v.Sizing)
	decPadding(m, p+24, &v.Padding)
	v.ChildGap = uint16(getU16(m, p+32))
	decChildAlignment(m, p+34, &v.ChildAlignment)
	v.LayoutDirection = LayoutDirection(getU8(m, p+36))
}

type AspectRatioElementConfig struct {
	AspectRatio float32
}

const sizeofAspectRatioElementConfig = 4

func encAspectRatioElementConfig(b []byte, p uint32, v *AspectRatioElementConfig) {
	putF32(b, p+0, v.AspectRatio)
}

func decAspectRatioElementConfig(m []byte, p uint32, v *AspectRatioElementConfig) {
	v.AspectRatio = getF32(m, p+0)
}

type ImageElementConfig struct {
	ImageData any
}

const sizeofImageElementConfig = 4

func encImageElementConfig(b []byte, p uint32, v *ImageElementConfig) {
	putU32(b, p+0, storeHandle(v.ImageData))
}

func decImageElementConfig(m []byte, p uint32, v *ImageElementConfig) {
	v.ImageData = loadHandle(getU32(m, p+0))
}

type FloatingAttachPoints struct {
	Element FloatingAttachPointType
	Parent  FloatingAttachPointType
}

const sizeofFloatingAttachPoints = 2

func encFloatingAttachPoints(b []byte, p uint32, v *FloatingAttachPoints) {
	putU8(b, p+0, uint8(v.Element))
	putU8(b, p+1, uint8(v.Parent))
}

func decFloatingAttachPoints(m []byte, p uint32, v *FloatingAttachPoints) {
	v.Element = FloatingAttachPointType(getU8(m, p+0))
	v.Parent = FloatingAttachPointType(getU8(m, p+1))
}

type FloatingElementConfig struct {
	Offset             Vector2
	Expand             Dimensions
	ParentId           uint32
	ZIndex             int16
	AttachPoints       FloatingAttachPoints
	PointerCaptureMode PointerCaptureMode
	AttachTo           FloatingAttachToElement
	ClipTo             FloatingClipToElement
}

const sizeofFloatingElementConfig = 28

func encFloatingElementConfig(b []byte, p uint32, v *FloatingElementConfig) {
	encVector2(b, p+0, &v.Offset)
	encDimensions(b, p+8, &v.Expand)
	putU32(b, p+16, uint32(v.ParentId))
	putU16(b, p+20, uint16(v.ZIndex))
	encFloatingAttachPoints(b, p+22, &v.AttachPoints)
	putU8(b, p+24, uint8(v.PointerCaptureMode))
	putU8(b, p+25, uint8(v.AttachTo))
	putU8(b, p+26, uint8(v.ClipTo))
}

func decFloatingElementConfig(m []byte, p uint32, v *FloatingElementConfig) {
	decVector2(m, p+0, &v.Offset)
	decDimensions(m, p+8, &v.Expand)
	v.ParentId = uint32(getU32(m, p+16))
	v.ZIndex = int16(getU16(m, p+20))
	decFloatingAttachPoints(m, p+22, &v.AttachPoints)
	v.PointerCaptureMode = PointerCaptureMode(getU8(m, p+24))
	v.AttachTo = FloatingAttachToElement(getU8(m, p+25))
	v.ClipTo = FloatingClipToElement(getU8(m, p+26))
}

type CustomElementConfig struct {
	CustomData any
}

const sizeofCustomElementConfig = 4

func encCustomElementConfig(b []byte, p uint32, v *CustomElementConfig) {
	putU32(b, p+0, storeHandle(v.CustomData))
}

func decCustomElementConfig(m []byte, p uint32, v *CustomElementConfig) {
	v.CustomData = loadHandle(getU32(m, p+0))
}

type BorderElementConfig struct {
	Color Color
	Width BorderWidth
}

const sizeofBorderElementConfig = 28

func encBorderElementConfig(b []byte, p uint32, v *BorderElementConfig) {
	encColor(b, p+0, &v.Color)
	encBorderWidth(b, p+16, &v.Width)
}

func decBorderElementConfig(m []byte, p uint32, v *BorderElementConfig) {
	decColor(m, p+0, &v.Color)
	decBorderWidth(m, p+16, &v.Width)
}

type TransitionElementConfig struct {
	Duration            float32
	Properties          TransitionProperty
	InteractionHandling TransitionInteractionHandlingType
	Enter               struct {
		Trigger TransitionEnterTriggerType
	}
	Exit struct {
		Trigger         TransitionExitTriggerType
		SiblingOrdering ExitTransitionSiblingOrdering
	}
}

const sizeofTransitionElementConfig = 32

func encTransitionElementConfig(b []byte, p uint32, v *TransitionElementConfig) {
	putF32(b, p+4, v.Duration)
	putU32(b, p+8, uint32(v.Properties))
	putU8(b, p+12, uint8(v.InteractionHandling))
	putU8(b, p+16+4, uint8(v.Enter.Trigger))

	putU8(b, p+24+4, uint8(v.Exit.Trigger))
	putU8(b, p+24+5, uint8(v.Exit.SiblingOrdering))

}

func decTransitionElementConfig(m []byte, p uint32, v *TransitionElementConfig) {
	v.Duration = getF32(m, p+4)
	v.Properties = TransitionProperty(getU32(m, p+8))
	v.InteractionHandling = TransitionInteractionHandlingType(getU8(m, p+12))
	v.Enter.Trigger = TransitionEnterTriggerType(getU8(m, p+16+4))

	v.Exit.Trigger = TransitionExitTriggerType(getU8(m, p+24+4))
	v.Exit.SiblingOrdering = ExitTransitionSiblingOrdering(getU8(m, p+24+5))

}

type ElementDeclaration struct {
	Layout          LayoutConfig
	BackgroundColor Color
	OverlayColor    Color
	CornerRadius    CornerRadius
	AspectRatio     AspectRatioElementConfig
	Image           ImageElementConfig
	Floating        FloatingElementConfig
	Custom          CustomElementConfig
	Clip            ClipElementConfig
	Border          BorderElementConfig
	Transition      TransitionElementConfig
	UserData        any
}

const sizeofElementDeclaration = 204

func encElementDeclaration(b []byte, p uint32, v *ElementDeclaration) {
	encLayoutConfig(b, p+0, &v.Layout)
	encColor(b, p+40, &v.BackgroundColor)
	encColor(b, p+56, &v.OverlayColor)
	encCornerRadius(b, p+72, &v.CornerRadius)
	encAspectRatioElementConfig(b, p+88, &v.AspectRatio)
	encImageElementConfig(b, p+92, &v.Image)
	encFloatingElementConfig(b, p+96, &v.Floating)
	encCustomElementConfig(b, p+124, &v.Custom)
	encClipElementConfig(b, p+128, &v.Clip)
	encBorderElementConfig(b, p+140, &v.Border)
	encTransitionElementConfig(b, p+168, &v.Transition)
	putU32(b, p+200, storeHandle(v.UserData))
}

func decElementDeclaration(m []byte, p uint32, v *ElementDeclaration) {
	decLayoutConfig(m, p+0, &v.Layout)
	decColor(m, p+40, &v.BackgroundColor)
	decColor(m, p+56, &v.OverlayColor)
	decCornerRadius(m, p+72, &v.CornerRadius)
	decAspectRatioElementConfig(m, p+88, &v.AspectRatio)
	decImageElementConfig(m, p+92, &v.Image)
	decFloatingElementConfig(m, p+96, &v.Floating)
	decCustomElementConfig(m, p+124, &v.Custom)
	decClipElementConfig(m, p+128, &v.Clip)
	decBorderElementConfig(m, p+140, &v.Border)
	decTransitionElementConfig(m, p+168, &v.Transition)
	v.UserData = loadHandle(getU32(m, p+200))
}

type TextElementConfig struct {
	UserData      any
	TextColor     Color
	FontId        uint16
	FontSize      uint16
	LetterSpacing uint16
	LineHeight    uint16
	WrapMode      TextElementConfigWrapMode
	TextAlignment TextAlignment
}

const sizeofTextElementConfig = 32

func encTextElementConfig(b []byte, p uint32, v *TextElementConfig) {
	putU32(b, p+0, storeHandle(v.UserData))
	encColor(b, p+4, &v.TextColor)
	putU16(b, p+20, uint16(v.FontId))
	putU16(b, p+22, uint16(v.FontSize))
	putU16(b, p+24, uint16(v.LetterSpacing))
	putU16(b, p+26, uint16(v.LineHeight))
	putU8(b, p+28, uint8(v.WrapMode))
	putU8(b, p+29, uint8(v.TextAlignment))
}

func decTextElementConfig(m []byte, p uint32, v *TextElementConfig) {
	v.UserData = loadHandle(getU32(m, p+0))
	decColor(m, p+4, &v.TextColor)
	v.FontId = uint16(getU16(m, p+20))
	v.FontSize = uint16(getU16(m, p+22))
	v.LetterSpacing = uint16(getU16(m, p+24))
	v.LineHeight = uint16(getU16(m, p+26))
	v.WrapMode = TextElementConfigWrapMode(getU8(m, p+28))
	v.TextAlignment = TextAlignment(getU8(m, p+29))
}

type ErrorData struct {
	ErrorType ErrorType
	ErrorText string
	UserData  any
}

const sizeofErrorData = 20

func encErrorData(b []byte, p uint32, v *ErrorData) {
	putU8(b, p+0, uint8(v.ErrorType))
	encString(b, p+4, &v.ErrorText)
	putU32(b, p+16, storeHandle(v.UserData))
}

func decErrorData(m []byte, p uint32, v *ErrorData) {
	v.ErrorType = ErrorType(getU8(m, p+0))
	decString(m, p+4, &v.ErrorText)
	v.UserData = loadHandle(getU32(m, p+16))
}

func MinMemorySize() uint32 {
	return uint32(module.Xgo_Clay_MinMemorySize())
}

func SetPointerState(position Vector2, pointerDown bool) {
	argBuf := wasmArgs(8)
	encVector2(argBuf, 0, &position)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay_SetPointerState(int32(argPtr+0), b2i(pointerDown))
}

func GetPointerState() PointerData {
	argPtr := scratchAddr
	var ret PointerData
	module.Xgo_Clay_GetPointerState(int32(argPtr + 0))
	decPointerData(wasmMemory(), argPtr+0, &ret)
	return ret
}

func GetCurrentContext() *Context {
	return contextOf(uint32(module.Xgo_Clay_GetCurrentContext()))
}

func SetCurrentContext(context *Context) {
	module.Xgo_Clay_SetCurrentContext(context.wasmAddr())
}

func UpdateScrollContainers(enableDragScrolling bool, scrollDelta Vector2, deltaTime float32) {
	argBuf := wasmArgs(8)
	encVector2(argBuf, 0, &scrollDelta)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay_UpdateScrollContainers(b2i(enableDragScrolling), int32(argPtr+0), float32(deltaTime))
}

func GetScrollOffset() Vector2 {
	argPtr := scratchAddr
	var ret Vector2
	module.Xgo_Clay_GetScrollOffset(int32(argPtr + 0))
	decVector2(wasmMemory(), argPtr+0, &ret)
	return ret
}

func SetLayoutDimensions(dimensions Dimensions) {
	argBuf := wasmArgs(8)
	encDimensions(argBuf, 0, &dimensions)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay_SetLayoutDimensions(int32(argPtr + 0))
}

func GetLayoutDimensions() Dimensions {
	argPtr := scratchAddr
	var ret Dimensions
	module.Xgo_Clay_GetLayoutDimensions(int32(argPtr + 0))
	decDimensions(wasmMemory(), argPtr+0, &ret)
	return ret
}

func beginLayout() {
	module.Xgo_Clay_BeginLayout()
}

var endLayoutResult RenderCommandArray

// The returned slice is reused by the next call to EndLayout.
func EndLayout(deltaTime float32) RenderCommandArray {
	argPtr := scratchAddr
	module.Xgo_Clay_EndLayout(int32(argPtr+0), float32(deltaTime))
	decRenderCommandArray(wasmMemory(), argPtr+0, &endLayoutResult)
	return endLayoutResult
}

func GetOpenElementId() uint32 {
	return uint32(module.Xgo_Clay_GetOpenElementId())
}

func GetElementId(idString string) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &idString)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay_GetElementId(int32(argPtr+16), int32(argPtr+0))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

func GetElementIdWithIndex(idString string, index uint32) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &idString)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay_GetElementIdWithIndex(int32(argPtr+16), int32(argPtr+0), int32(index))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

func GetElementData(id ElementId) ElementData {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &id)
	argPtr := wasmCommit(argBuf)
	var ret ElementData
	module.Xgo_Clay_GetElementData(int32(argPtr+24), int32(argPtr+0))
	decElementData(wasmMemory(), argPtr+24, &ret)
	return ret
}

func Hovered() bool {
	return module.Xgo_Clay_Hovered() != 0
}

func PointerOver(elementId ElementId) bool {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &elementId)
	argPtr := wasmCommit(argBuf)
	return module.Xgo_Clay_PointerOver(int32(argPtr+0)) != 0
}

var getPointerOverIdsResult ElementIdArray

// The returned slice is reused by the next call to GetPointerOverIds.
func GetPointerOverIds() ElementIdArray {
	argPtr := scratchAddr
	module.Xgo_Clay_GetPointerOverIds(int32(argPtr + 0))
	decElementIdArray(wasmMemory(), argPtr+0, &getPointerOverIdsResult)
	return getPointerOverIdsResult
}

func GetScrollContainerData(id ElementId) ScrollContainerData {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &id)
	argPtr := wasmCommit(argBuf)
	var ret ScrollContainerData
	module.Xgo_Clay_GetScrollContainerData(int32(argPtr+24), int32(argPtr+0))
	decScrollContainerData(wasmMemory(), argPtr+24, &ret)
	return ret
}

func SetDebugModeEnabled(enabled bool) {
	module.Xgo_Clay_SetDebugModeEnabled(b2i(enabled))
}

func IsDebugModeEnabled() bool {
	return module.Xgo_Clay_IsDebugModeEnabled() != 0
}

func SetCullingEnabled(enabled bool) {
	module.Xgo_Clay_SetCullingEnabled(b2i(enabled))
}

func GetMaxElementCount() int32 {
	return int32(module.Xgo_Clay_GetMaxElementCount())
}

func SetMaxElementCount(maxElementCount int32) {
	module.Xgo_Clay_SetMaxElementCount(int32(maxElementCount))
}

func GetMaxMeasureTextCacheWordCount() int32 {
	return int32(module.Xgo_Clay_GetMaxMeasureTextCacheWordCount())
}

func SetMaxMeasureTextCacheWordCount(maxMeasureTextCacheWordCount int32) {
	module.Xgo_Clay_SetMaxMeasureTextCacheWordCount(int32(maxMeasureTextCacheWordCount))
}

func ResetMeasureTextCache() {
	module.Xgo_Clay_ResetMeasureTextCache()
}

func __OpenElement() {
	module.Xgo_Clay__OpenElement()
}

func __OpenElementWithId(elementId ElementId) {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &elementId)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay__OpenElementWithId(int32(argPtr + 0))
}

func __ConfigureOpenElement(config ElementDeclaration) {
	argBuf := wasmArgs(204)
	encElementDeclaration(argBuf, 0, &config)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay__ConfigureOpenElement(int32(argPtr + 0))
}

func __CloseElement() {
	module.Xgo_Clay__CloseElement()
}

func __HashString(key string, seed uint32) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &key)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay__HashString(int32(argPtr+16), int32(argPtr+0), int32(seed))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

func __HashStringWithOffset(key string, offset uint32, seed uint32) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &key)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay__HashStringWithOffset(int32(argPtr+16), int32(argPtr+0), int32(offset), int32(seed))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

func decodeValue(m []byte, p uint32, v any) {
	switch v := v.(type) {
	case *Vector2:
		decVector2(m, p, v)
	case *TransitionData:
		decTransitionData(m, p, v)
	default:
		panic("clay: unsupported pointer type")
	}
}

func encodeValue(b []byte, p uint32, v any) uint32 {
	switch v := v.(type) {
	case *Vector2:
		encVector2(b, p, v)
		return sizeofVector2
	case *TransitionData:
		encTransitionData(b, p, v)
		return sizeofTransitionData
	default:
		panic("clay: unsupported pointer type")
	}
}
