// Code generated by internal/cmd/generate from clay.h; DO NOT EDIT.

package clay

// Represents the current state of interaction with clay this frame.
type PointerDataInteractionState uint8

const (
	// A left mouse click, or touch occurred this frame.
	POINTER_DATA_PRESSED_THIS_FRAME PointerDataInteractionState = 0
	// The left mouse button click or touch happened at some point in the past, and is still currently held down this frame.
	POINTER_DATA_PRESSED PointerDataInteractionState = 1
	// The left mouse button click or touch was released this frame.
	POINTER_DATA_RELEASED_THIS_FRAME PointerDataInteractionState = 2
	// The left mouse button click or touch is not currently down / was released at some point in the past.
	POINTER_DATA_RELEASED PointerDataInteractionState = 3
)

// Used by renderers to determine specific handling for each render command.
type RenderCommandType uint8

const (
	// This command type should be skipped.
	RENDER_COMMAND_TYPE_NONE RenderCommandType = 0
	// The renderer should draw a solid color rectangle.
	RENDER_COMMAND_TYPE_RECTANGLE RenderCommandType = 1
	// The renderer should draw a colored border inset into the bounding box.
	RENDER_COMMAND_TYPE_BORDER RenderCommandType = 2
	// The renderer should draw text.
	RENDER_COMMAND_TYPE_TEXT RenderCommandType = 3
	// The renderer should draw an image.
	RENDER_COMMAND_TYPE_IMAGE RenderCommandType = 4
	// The renderer should begin clipping all future draw commands, only rendering content that falls within the provided boundingBox.
	RENDER_COMMAND_TYPE_SCISSOR_START RenderCommandType = 5
	// The renderer should finish any previously active clipping, and begin rendering elements in full again.
	RENDER_COMMAND_TYPE_SCISSOR_END RenderCommandType = 6
	// The renderer should begin performing a "color overlay" on all subsequent render commands until disabled again.
	RENDER_COMMAND_TYPE_OVERLAY_COLOR_START RenderCommandType = 7
	// The renderer should disable any previously active "color overlay" and render elements with their standard colors again.
	RENDER_COMMAND_TYPE_OVERLAY_COLOR_END RenderCommandType = 8
	// The renderer should provide a custom implementation for handling this render command based on its .customData
	RENDER_COMMAND_TYPE_CUSTOM RenderCommandType = 9
)

type TransitionState int32

const (
	TRANSITION_STATE_IDLE          TransitionState = 0
	TRANSITION_STATE_ENTERING      TransitionState = 1
	TRANSITION_STATE_TRANSITIONING TransitionState = 2
	TRANSITION_STATE_EXITING       TransitionState = 3
)

type TransitionProperty int32

const (
	TRANSITION_PROPERTY_NONE             TransitionProperty = 0
	TRANSITION_PROPERTY_X                TransitionProperty = 1
	TRANSITION_PROPERTY_Y                TransitionProperty = 2
	TRANSITION_PROPERTY_POSITION         TransitionProperty = 3
	TRANSITION_PROPERTY_WIDTH            TransitionProperty = 4
	TRANSITION_PROPERTY_HEIGHT           TransitionProperty = 8
	TRANSITION_PROPERTY_DIMENSIONS       TransitionProperty = 12
	TRANSITION_PROPERTY_BOUNDING_BOX     TransitionProperty = 15
	TRANSITION_PROPERTY_BACKGROUND_COLOR TransitionProperty = 16
	TRANSITION_PROPERTY_OVERLAY_COLOR    TransitionProperty = 32
	TRANSITION_PROPERTY_CORNER_RADIUS    TransitionProperty = 64
	TRANSITION_PROPERTY_BORDER_COLOR     TransitionProperty = 128
	TRANSITION_PROPERTY_BORDER_WIDTH     TransitionProperty = 256
	TRANSITION_PROPERTY_BORDER           TransitionProperty = 384
)

// Controls how the element takes up space inside its parent container.
type __SizingType uint8

const (
	// (default) Wraps tightly to the size of the element's contents.
	__SIZING_TYPE_FIT __SizingType = 0
	// Expands along this axis to fill available space in the parent element, sharing it with other GROW elements.
	__SIZING_TYPE_GROW __SizingType = 1
	// Expects 0-1 range. Clamps the axis size to a percent of the parent container's axis size minus padding and child gaps.
	__SIZING_TYPE_PERCENT __SizingType = 2
	// Clamps the axis size to an exact size in pixels.
	__SIZING_TYPE_FIXED __SizingType = 3
)

// Controls the alignment along the x axis (horizontal) of child elements.
type LayoutAlignmentX uint8

const (
	// (Default) Aligns child elements to the left hand side of this element, offset by padding.width.left
	ALIGN_X_LEFT LayoutAlignmentX = 0
	// Aligns child elements to the right hand side of this element, offset by padding.width.right
	ALIGN_X_RIGHT LayoutAlignmentX = 1
	// Aligns child elements horizontally to the center of this element
	ALIGN_X_CENTER LayoutAlignmentX = 2
)

// Controls the alignment along the y axis (vertical) of child elements.
type LayoutAlignmentY uint8

const (
	// (Default) Aligns child elements to the top of this element, offset by padding.width.top
	ALIGN_Y_TOP LayoutAlignmentY = 0
	// Aligns child elements to the bottom of this element, offset by padding.width.bottom
	ALIGN_Y_BOTTOM LayoutAlignmentY = 1
	// Aligns child elements vertically to the center of this element
	ALIGN_Y_CENTER LayoutAlignmentY = 2
)

// Controls the direction in which child elements will be automatically laid out.
type LayoutDirection uint8

const (
	// (Default) Lays out child elements from left to right with increasing x.
	LEFT_TO_RIGHT LayoutDirection = 0
	// Lays out child elements from top to bottom with increasing y.
	TOP_TO_BOTTOM LayoutDirection = 1
)

// Controls where a floating element is offset relative to its parent element.
// Note: see https://github.com/user-attachments/assets/b8c6dfaa-c1b1-41a4-be55-013473e4a6ce for a visual explanation.
type FloatingAttachPointType uint8

const (
	ATTACH_POINT_LEFT_TOP      FloatingAttachPointType = 0
	ATTACH_POINT_LEFT_CENTER   FloatingAttachPointType = 1
	ATTACH_POINT_LEFT_BOTTOM   FloatingAttachPointType = 2
	ATTACH_POINT_CENTER_TOP    FloatingAttachPointType = 3
	ATTACH_POINT_CENTER_CENTER FloatingAttachPointType = 4
	ATTACH_POINT_CENTER_BOTTOM FloatingAttachPointType = 5
	ATTACH_POINT_RIGHT_TOP     FloatingAttachPointType = 6
	ATTACH_POINT_RIGHT_CENTER  FloatingAttachPointType = 7
	ATTACH_POINT_RIGHT_BOTTOM  FloatingAttachPointType = 8
)

// Controls how mouse pointer events like hover and click are captured or passed through to elements underneath a floating element.
type PointerCaptureMode uint8

const (
	// (default) "Capture" the pointer event and don't allow events like hover and click to pass through to elements underneath.
	POINTER_CAPTURE_MODE_CAPTURE PointerCaptureMode = 0
	// CLAY_POINTER_CAPTURE_MODE_PARENT, TODO pass pointer through to attached parent
	// Transparently pass through pointer events like hover and click to elements underneath the floating element.
	POINTER_CAPTURE_MODE_PASSTHROUGH PointerCaptureMode = 1
)

// Controls which element a floating element is "attached" to (i.e. relative offset from).
type FloatingAttachToElement uint8

const (
	// (default) Disables floating for this element.
	ATTACH_TO_NONE FloatingAttachToElement = 0
	// Attaches this floating element to its parent, positioned based on the .attachPoints and .offset fields.
	ATTACH_TO_PARENT FloatingAttachToElement = 1
	// Attaches this floating element to an element with a specific ID, specified with the .parentId field. positioned based on the .attachPoints and .offset fields.
	ATTACH_TO_ELEMENT_WITH_ID FloatingAttachToElement = 2
	// Attaches this floating element to the root of the layout, which combined with the .offset field provides functionality similar to "absolute positioning".
	ATTACH_TO_ROOT FloatingAttachToElement = 3
)

// Controls whether or not a floating element is clipped to the same clipping rectangle as the element it's attached to.
type FloatingClipToElement uint8

const (
	// (default) - The floating element does not inherit clipping.
	CLIP_TO_NONE FloatingClipToElement = 0
	// The floating element is clipped to the same clipping rectangle as the element it's attached to.
	CLIP_TO_ATTACHED_PARENT FloatingClipToElement = 1
)

type TransitionInteractionHandlingType uint8

const (
	TRANSITION_DISABLE_INTERACTIONS_WHILE_TRANSITIONING_POSITION TransitionInteractionHandlingType = 0
	TRANSITION_ALLOW_INTERACTIONS_WHILE_TRANSITIONING_POSITION   TransitionInteractionHandlingType = 1
)

type TransitionEnterTriggerType uint8

const (
	TRANSITION_ENTER_SKIP_ON_FIRST_PARENT_FRAME    TransitionEnterTriggerType = 0
	TRANSITION_ENTER_TRIGGER_ON_FIRST_PARENT_FRAME TransitionEnterTriggerType = 1
)

type TransitionExitTriggerType uint8

const (
	TRANSITION_EXIT_SKIP_WHEN_PARENT_EXITS    TransitionExitTriggerType = 0
	TRANSITION_EXIT_TRIGGER_WHEN_PARENT_EXITS TransitionExitTriggerType = 1
)

type ExitTransitionSiblingOrdering uint8

const (
	EXIT_TRANSITION_ORDERING_UNDERNEATH_SIBLINGS ExitTransitionSiblingOrdering = 0
	EXIT_TRANSITION_ORDERING_NATURAL_ORDER       ExitTransitionSiblingOrdering = 1
	EXIT_TRANSITION_ORDERING_ABOVE_SIBLINGS      ExitTransitionSiblingOrdering = 2
)

// Controls how text "wraps", that is how it is broken into multiple lines when there is insufficient horizontal space.
type TextElementConfigWrapMode uint8

const (
	// (default) breaks on whitespace characters.
	TEXT_WRAP_WORDS TextElementConfigWrapMode = 0
	// Don't break on space characters, only on newlines.
	TEXT_WRAP_NEWLINES TextElementConfigWrapMode = 1
	// Disable text wrapping entirely.
	TEXT_WRAP_NONE TextElementConfigWrapMode = 2
)

// Controls how wrapped lines of text are horizontally aligned within the outer text bounding box.
type TextAlignment uint8

const (
	// (default) Horizontally aligns wrapped lines of text to the left hand side of their bounding box.
	TEXT_ALIGN_LEFT TextAlignment = 0
	// Horizontally aligns wrapped lines of text to the center of their bounding box.
	TEXT_ALIGN_CENTER TextAlignment = 1
	// Horizontally aligns wrapped lines of text to the right hand side of their bounding box.
	TEXT_ALIGN_RIGHT TextAlignment = 2
)

// Represents the type of error clay encountered while computing layout.
type ErrorType uint8

const (
	// A text measurement function wasn't provided using SetMeasureTextFunction(), or the provided function was null.
	ERROR_TYPE_TEXT_MEASUREMENT_FUNCTION_NOT_PROVIDED ErrorType = 0
	// Clay attempted to allocate its internal data structures but ran out of space.
	// The arena passed to Initialize was created with a capacity smaller than that required by MinMemorySize().
	ERROR_TYPE_ARENA_CAPACITY_EXCEEDED ErrorType = 1
	// Clay ran out of capacity in its internal array for storing elements. This limit can be increased with SetMaxElementCount().
	ERROR_TYPE_ELEMENTS_CAPACITY_EXCEEDED ErrorType = 2
	// Clay ran out of capacity in its internal array for storing elements. This limit can be increased with SetMaxMeasureTextCacheWordCount().
	ERROR_TYPE_TEXT_MEASUREMENT_CAPACITY_EXCEEDED ErrorType = 3
	// Two elements were declared with exactly the same ID within one layout.
	ERROR_TYPE_DUPLICATE_ID ErrorType = 4
	// A floating element was declared using CLAY_ATTACH_TO_ELEMENT_ID and either an invalid .parentId was provided or no element with the provided .parentId was found.
	ERROR_TYPE_FLOATING_CONTAINER_PARENT_NOT_FOUND ErrorType = 5
	// An element was declared that using CLAY_SIZING_PERCENT but the percentage value was over 1. Percentage values are expected to be in the 0-1 range.
	ERROR_TYPE_PERCENTAGE_OVER_1 ErrorType = 6
	// Clay encountered an internal error. It would be wonderful if you could report this so we can fix it!
	ERROR_TYPE_INTERNAL_ERROR ErrorType = 7
	// __OpenElement was called more times than __CloseElement, so there were still remaining open elements when the layout ended.
	ERROR_TYPE_UNBALANCED_OPEN_CLOSE      ErrorType = 8
	ERROR_TYPE_HASH_MAP_CAPACITY_EXCEEDED ErrorType = 9
)

type Vector2 struct {
	X float32
	Y float32
}

const sizeofVector2 = 8

func encVector2(b []byte, p uint32, v *Vector2) {
	putF32(b, p+0, v.X)
	putF32(b, p+4, v.Y)
}

func decVector2(m []byte, p uint32, v *Vector2) {
	v.X = getF32(m, p+0)
	v.Y = getF32(m, p+4)
}

// Information on the current state of pointer interactions this frame.
type PointerData struct {
	// The position of the mouse / touch / pointer relative to the root of the layout.
	Position Vector2
	// Represents the current state of interaction with clay this frame.
	// POINTER_DATA_PRESSED_THIS_FRAME - A left mouse click, or touch occurred this frame.
	// POINTER_DATA_PRESSED - The left mouse button click or touch happened at some point in the past, and is still currently held down this frame.
	// POINTER_DATA_RELEASED_THIS_FRAME - The left mouse button click or touch was released this frame.
	// POINTER_DATA_RELEASED - The left mouse button click or touch is not currently down / was released at some point in the past.
	State PointerDataInteractionState
}

const sizeofPointerData = 12

func encPointerData(b []byte, p uint32, v *PointerData) {
	encVector2(b, p+0, &v.Position)
	putU8(b, p+8, uint8(v.State))
}

func decPointerData(m []byte, p uint32, v *PointerData) {
	decVector2(m, p+0, &v.Position)
	v.State = PointerDataInteractionState(getU8(m, p+8))
}

type Dimensions struct {
	Width  float32
	Height float32
}

const sizeofDimensions = 8

func encDimensions(b []byte, p uint32, v *Dimensions) {
	putF32(b, p+0, v.Width)
	putF32(b, p+4, v.Height)
}

func decDimensions(m []byte, p uint32, v *Dimensions) {
	v.Width = getF32(m, p+0)
	v.Height = getF32(m, p+4)
}

type BoundingBox struct {
	X      float32
	Y      float32
	Width  float32
	Height float32
}

const sizeofBoundingBox = 16

func encBoundingBox(b []byte, p uint32, v *BoundingBox) {
	putF32(b, p+0, v.X)
	putF32(b, p+4, v.Y)
	putF32(b, p+8, v.Width)
	putF32(b, p+12, v.Height)
}

func decBoundingBox(m []byte, p uint32, v *BoundingBox) {
	v.X = getF32(m, p+0)
	v.Y = getF32(m, p+4)
	v.Width = getF32(m, p+8)
	v.Height = getF32(m, p+12)
}

// Internally clay conventionally represents colors as 0-255, but interpretation is up to the renderer.
type Color struct {
	R float32
	G float32
	B float32
	A float32
}

const sizeofColor = 16

func encColor(b []byte, p uint32, v *Color) {
	putF32(b, p+0, v.R)
	putF32(b, p+4, v.G)
	putF32(b, p+8, v.B)
	putF32(b, p+12, v.A)
}

func decColor(m []byte, p uint32, v *Color) {
	v.R = getF32(m, p+0)
	v.G = getF32(m, p+4)
	v.B = getF32(m, p+8)
	v.A = getF32(m, p+12)
}

// Controls the "radius", or corner rounding of elements, including rectangles, borders and images.
// The rounding is determined by drawing a circle inset into the element corner by (radius, radius) pixels.
type CornerRadius struct {
	TopLeft     float32
	TopRight    float32
	BottomLeft  float32
	BottomRight float32
}

const sizeofCornerRadius = 16

func encCornerRadius(b []byte, p uint32, v *CornerRadius) {
	putF32(b, p+0, v.TopLeft)
	putF32(b, p+4, v.TopRight)
	putF32(b, p+8, v.BottomLeft)
	putF32(b, p+12, v.BottomRight)
}

func decCornerRadius(m []byte, p uint32, v *CornerRadius) {
	v.TopLeft = getF32(m, p+0)
	v.TopRight = getF32(m, p+4)
	v.BottomLeft = getF32(m, p+8)
	v.BottomRight = getF32(m, p+12)
}

// Render command data when commandType == RENDER_COMMAND_TYPE_RECTANGLE
type RectangleRenderData struct {
	// The solid background color to fill this rectangle with. Conventionally represented as 0-255 for each channel, but interpretation is up to the renderer.
	BackgroundColor Color
	// Controls the "radius", or corner rounding of elements, including rectangles, borders and images.
	// The rounding is determined by drawing a circle inset into the element corner by (radius, radius) pixels.
	CornerRadius CornerRadius
}

const sizeofRectangleRenderData = 32

func encRectangleRenderData(b []byte, p uint32, v *RectangleRenderData) {
	encColor(b, p+0, &v.BackgroundColor)
	encCornerRadius(b, p+16, &v.CornerRadius)
}

func decRectangleRenderData(m []byte, p uint32, v *RectangleRenderData) {
	decColor(m, p+0, &v.BackgroundColor)
	decCornerRadius(m, p+16, &v.CornerRadius)
}

const sizeofStringSlice = 12

func encStringSlice(b []byte, p uint32, v *string) {
	addr := storeString(*v)
	putU32(b, p+4, addr)
	putU32(b, p+0, uint32(len(*v)))
	putU32(b, p+8, addr)
}

func decStringSlice(m []byte, p uint32, v *string) {
	*v = loadString(m, getU32(m, p+4), getU32(m, p+0))
}

// Render command data when commandType == RENDER_COMMAND_TYPE_TEXT
type TextRenderData struct {
	// A string slice containing the text to be rendered.
	// Note: this is not guaranteed to be null terminated.
	StringContents string
	// Conventionally represented as 0-255 for each channel, but interpretation is up to the renderer.
	TextColor Color
	// An integer representing the font to use to render this text, transparently passed through from the text declaration.
	FontId   uint16
	FontSize uint16
	// Specifies the extra whitespace gap in pixels between each character.
	LetterSpacing uint16
	// The height of the bounding box for this line of text.
	LineHeight uint16
}

const sizeofTextRenderData = 36

func encTextRenderData(b []byte, p uint32, v *TextRenderData) {
	encStringSlice(b, p+0, &v.StringContents)
	encColor(b, p+12, &v.TextColor)
	putU16(b, p+28, uint16(v.FontId))
	putU16(b, p+30, uint16(v.FontSize))
	putU16(b, p+32, uint16(v.LetterSpacing))
	putU16(b, p+34, uint16(v.LineHeight))
}

func decTextRenderData(m []byte, p uint32, v *TextRenderData) {
	decStringSlice(m, p+0, &v.StringContents)
	decColor(m, p+12, &v.TextColor)
	v.FontId = uint16(getU16(m, p+28))
	v.FontSize = uint16(getU16(m, p+30))
	v.LetterSpacing = uint16(getU16(m, p+32))
	v.LineHeight = uint16(getU16(m, p+34))
}

// Render command data when commandType == RENDER_COMMAND_TYPE_IMAGE
type ImageRenderData struct {
	// The tint color for this image. Note that the default value is 0,0,0,0 and should likely be interpreted
	// as "untinted".
	// Conventionally represented as 0-255 for each channel, but interpretation is up to the renderer.
	BackgroundColor Color
	// Controls the "radius", or corner rounding of this image.
	// The rounding is determined by drawing a circle inset into the element corner by (radius, radius) pixels.
	CornerRadius CornerRadius
	// A pointer transparently passed through from the original element definition, typically used to represent image data.
	ImageData any
}

const sizeofImageRenderData = 36

func encImageRenderData(b []byte, p uint32, v *ImageRenderData) {
	encColor(b, p+0, &v.BackgroundColor)
	encCornerRadius(b, p+16, &v.CornerRadius)
	putU32(b, p+32, storeHandle(v.ImageData))
}

func decImageRenderData(m []byte, p uint32, v *ImageRenderData) {
	decColor(m, p+0, &v.BackgroundColor)
	decCornerRadius(m, p+16, &v.CornerRadius)
	v.ImageData = loadHandle(getU32(m, p+32))
}

// Render command data when commandType == RENDER_COMMAND_TYPE_CUSTOM
type CustomRenderData struct {
	// Passed through from .backgroundColor in the original element declaration.
	// Conventionally represented as 0-255 for each channel, but interpretation is up to the renderer.
	BackgroundColor Color
	// Controls the "radius", or corner rounding of this custom element.
	// The rounding is determined by drawing a circle inset into the element corner by (radius, radius) pixels.
	CornerRadius CornerRadius
	// A pointer transparently passed through from the original element definition.
	CustomData any
}

const sizeofCustomRenderData = 36

func encCustomRenderData(b []byte, p uint32, v *CustomRenderData) {
	encColor(b, p+0, &v.BackgroundColor)
	encCornerRadius(b, p+16, &v.CornerRadius)
	putU32(b, p+32, storeHandle(v.CustomData))
}

func decCustomRenderData(m []byte, p uint32, v *CustomRenderData) {
	decColor(m, p+0, &v.BackgroundColor)
	decCornerRadius(m, p+16, &v.CornerRadius)
	v.CustomData = loadHandle(getU32(m, p+32))
}

// Controls the widths of individual element borders.
type BorderWidth struct {
	Left   uint16
	Right  uint16
	Top    uint16
	Bottom uint16
	// Creates borders between each child element, depending on the .layoutDirection.
	// e.g. for LEFT_TO_RIGHT, borders will be vertical lines, and for TOP_TO_BOTTOM borders will be horizontal lines.
	// .betweenChildren borders will result in individual RECTANGLE render commands being generated.
	BetweenChildren uint16
}

const sizeofBorderWidth = 10

func encBorderWidth(b []byte, p uint32, v *BorderWidth) {
	putU16(b, p+0, uint16(v.Left))
	putU16(b, p+2, uint16(v.Right))
	putU16(b, p+4, uint16(v.Top))
	putU16(b, p+6, uint16(v.Bottom))
	putU16(b, p+8, uint16(v.BetweenChildren))
}

func decBorderWidth(m []byte, p uint32, v *BorderWidth) {
	v.Left = uint16(getU16(m, p+0))
	v.Right = uint16(getU16(m, p+2))
	v.Top = uint16(getU16(m, p+4))
	v.Bottom = uint16(getU16(m, p+6))
	v.BetweenChildren = uint16(getU16(m, p+8))
}

// Render command data when commandType == RENDER_COMMAND_TYPE_BORDER
type BorderRenderData struct {
	// Controls a shared color for all this element's borders.
	// Conventionally represented as 0-255 for each channel, but interpretation is up to the renderer.
	Color Color
	// Specifies the "radius", or corner rounding of this border element.
	// The rounding is determined by drawing a circle inset into the element corner by (radius, radius) pixels.
	CornerRadius CornerRadius
	// Controls individual border side widths.
	Width BorderWidth
}

const sizeofBorderRenderData = 44

func encBorderRenderData(b []byte, p uint32, v *BorderRenderData) {
	encColor(b, p+0, &v.Color)
	encCornerRadius(b, p+16, &v.CornerRadius)
	encBorderWidth(b, p+32, &v.Width)
}

func decBorderRenderData(m []byte, p uint32, v *BorderRenderData) {
	decColor(m, p+0, &v.Color)
	decCornerRadius(m, p+16, &v.CornerRadius)
	decBorderWidth(m, p+32, &v.Width)
}

// Render command data when commandType == RENDER_COMMAND_TYPE_SCISSOR_START || commandType == RENDER_COMMAND_TYPE_SCISSOR_END
type ClipRenderData struct {
	Horizontal bool
	Vertical   bool
}

const sizeofClipRenderData = 2

func encClipRenderData(b []byte, p uint32, v *ClipRenderData) {
	putBool(b, p+0, v.Horizontal)
	putBool(b, p+1, v.Vertical)
}

func decClipRenderData(m []byte, p uint32, v *ClipRenderData) {
	v.Horizontal = getBool(m, p+0)
	v.Vertical = getBool(m, p+1)
}

// Render command data when commandType == RENDER_COMMAND_TYPE_OVERLAY_COLOR_START || commandType == RENDER_COMMAND_TYPE_OVERLAY_COLOR_END
type OverlayColorRenderData struct {
	Color Color
}

const sizeofOverlayColorRenderData = 16

func encOverlayColorRenderData(b []byte, p uint32, v *OverlayColorRenderData) {
	encColor(b, p+0, &v.Color)
}

func decOverlayColorRenderData(m []byte, p uint32, v *OverlayColorRenderData) {
	decColor(m, p+0, &v.Color)
}

// A struct union containing data specific to this command's .commandType
type RenderData struct {
	// union
	// Render command data when commandType == RENDER_COMMAND_TYPE_RECTANGLE
	Rectangle RectangleRenderData
	// Render command data when commandType == RENDER_COMMAND_TYPE_TEXT
	Text TextRenderData
	// Render command data when commandType == RENDER_COMMAND_TYPE_IMAGE
	Image ImageRenderData
	// Render command data when commandType == RENDER_COMMAND_TYPE_CUSTOM
	Custom CustomRenderData
	// Render command data when commandType == RENDER_COMMAND_TYPE_BORDER
	Border BorderRenderData
	// Render command data when commandType == RENDER_COMMAND_TYPE_SCISSOR_START|END
	Clip ClipRenderData
	// Render command data when commandType == RENDER_COMMAND_TYPE_OVERLAY_COLOR_START|END
	OverlayColor OverlayColorRenderData
}

const sizeofRenderData = 44

type RenderCommand struct {
	// A rectangular box that fully encloses this UI element, with the position relative to the root of the layout.
	BoundingBox BoundingBox
	// A struct union containing data specific to this command's commandType.
	RenderData RenderData
	// A pointer transparently passed through from the original element declaration.
	UserData any
	// The id of this element, transparently passed through from the original element declaration.
	Id uint32
	// The z order required for drawing this command correctly.
	// Note: the render command array is already sorted in ascending order, and will produce correct results if drawn in naive order.
	// This field is intended for use in batching renderers for improved performance.
	ZIndex int16
	// Specifies how to handle rendering of this command.
	// RENDER_COMMAND_TYPE_RECTANGLE - The renderer should draw a solid color rectangle.
	// RENDER_COMMAND_TYPE_BORDER - The renderer should draw a colored border inset into the bounding box.
	// RENDER_COMMAND_TYPE_TEXT - The renderer should draw text.
	// RENDER_COMMAND_TYPE_IMAGE - The renderer should draw an image.
	// RENDER_COMMAND_TYPE_SCISSOR_START - The renderer should begin clipping all future draw commands, only rendering content that falls within the provided boundingBox.
	// RENDER_COMMAND_TYPE_SCISSOR_END - The renderer should finish any previously active clipping, and begin rendering elements in full again.
	// RENDER_COMMAND_TYPE_CUSTOM - The renderer should provide a custom implementation for handling this render command based on its .customData
	CommandType RenderCommandType
}

const sizeofRenderCommand = 72

func decRenderCommand(m []byte, p uint32, v *RenderCommand) {
	decBoundingBox(m, p+0, &v.BoundingBox)
	v.UserData = loadHandle(getU32(m, p+60))
	v.Id = uint32(getU32(m, p+64))
	v.ZIndex = int16(getU16(m, p+68))
	v.CommandType = RenderCommandType(getU8(m, p+70))
	v.RenderData = RenderData{}
	switch v.CommandType {
	case RENDER_COMMAND_TYPE_RECTANGLE:
		decRectangleRenderData(m, p+16+0, &v.RenderData.Rectangle)
	case RENDER_COMMAND_TYPE_BORDER:
		decBorderRenderData(m, p+16+0, &v.RenderData.Border)
	case RENDER_COMMAND_TYPE_TEXT:
		decTextRenderData(m, p+16+0, &v.RenderData.Text)
	case RENDER_COMMAND_TYPE_IMAGE:
		decImageRenderData(m, p+16+0, &v.RenderData.Image)
	case RENDER_COMMAND_TYPE_SCISSOR_START:
		decClipRenderData(m, p+16+0, &v.RenderData.Clip)
	case RENDER_COMMAND_TYPE_SCISSOR_END:
		decClipRenderData(m, p+16+0, &v.RenderData.Clip)
	case RENDER_COMMAND_TYPE_OVERLAY_COLOR_START:
		decOverlayColorRenderData(m, p+16+0, &v.RenderData.OverlayColor)
	case RENDER_COMMAND_TYPE_OVERLAY_COLOR_END:
		decOverlayColorRenderData(m, p+16+0, &v.RenderData.OverlayColor)
	case RENDER_COMMAND_TYPE_CUSTOM:
		decCustomRenderData(m, p+16+0, &v.RenderData.Custom)
	}
}

// A sized array of render commands.
type RenderCommandArray []RenderCommand

const sizeofRenderCommandArray = 12

func decRenderCommandArray(m []byte, p uint32, v *RenderCommandArray) {
	n := int(int32(getU32(m, p+4)))
	addr := getU32(m, p+8)
	s := (*v)[:0]
	if n <= 0 {
		*v = s
		return
	}
	if cap(s) < n {
		s = make(RenderCommandArray, n)
	}
	s = s[:n]
	for i := range s {
		decRenderCommand(m, addr+uint32(i)*72, &s[i])
	}
	*v = s
}

const sizeofString = 12

func encString(b []byte, p uint32, v *string) {
	addr := storeString(*v)
	putU32(b, p+8, addr)
	putU32(b, p+4, uint32(len(*v)))
}

func decString(m []byte, p uint32, v *string) {
	*v = loadString(m, getU32(m, p+8), getU32(m, p+4))
}

// Primarily created via the CLAY_ID(), CLAY_IDI(), CLAY_ID_LOCAL() and CLAY_IDI_LOCAL() macros.
// Represents a hashed string ID used for identifying and finding specific clay UI elements, required
// by functions such as PointerOver() and GetElementData().
type ElementId struct {
	// The resulting hash generated from the other fields.
	Id uint32
	// A numerical offset applied after computing the hash from stringId.
	Offset uint32
	// A base hash value to start from, for example the parent element ID is used when calculating CLAY_ID_LOCAL().
	BaseId uint32
	// The string id to hash.
	StringId string
}

const sizeofElementId = 24

func encElementId(b []byte, p uint32, v *ElementId) {
	putU32(b, p+0, uint32(v.Id))
	putU32(b, p+4, uint32(v.Offset))
	putU32(b, p+8, uint32(v.BaseId))
	encString(b, p+12, &v.StringId)
}

func decElementId(m []byte, p uint32, v *ElementId) {
	v.Id = uint32(getU32(m, p+0))
	v.Offset = uint32(getU32(m, p+4))
	v.BaseId = uint32(getU32(m, p+8))
	decString(m, p+12, &v.StringId)
}

// Bounding box and other data for a specific UI element.
type ElementData struct {
	// The rectangle that encloses this UI element, with the position relative to the root of the layout.
	BoundingBox BoundingBox
	// Indicates whether an actual Element matched the provided ID or if the default struct was returned.
	Found bool
}

const sizeofElementData = 20

func encElementData(b []byte, p uint32, v *ElementData) {
	encBoundingBox(b, p+0, &v.BoundingBox)
	putBool(b, p+16, v.Found)
}

func decElementData(m []byte, p uint32, v *ElementData) {
	decBoundingBox(m, p+0, &v.BoundingBox)
	v.Found = getBool(m, p+16)
}

// A sized array of ElementId.
type ElementIdArray []ElementId

const sizeofElementIdArray = 12

func decElementIdArray(m []byte, p uint32, v *ElementIdArray) {
	n := int(int32(getU32(m, p+4)))
	addr := getU32(m, p+8)
	s := (*v)[:0]
	if n <= 0 {
		*v = s
		return
	}
	if cap(s) < n {
		s = make(ElementIdArray, n)
	}
	s = s[:n]
	for i := range s {
		decElementId(m, addr+uint32(i)*24, &s[i])
	}
	*v = s
}

// Controls the axis on which an element switches to "scrolling", which clips the contents and allows scrolling in that direction.
type ClipElementConfig struct {
	// Clip overflowing elements on the X axis.
	Horizontal bool
	// Clip overflowing elements on the Y axis.
	Vertical bool
	// Offsets the x,y positions of all child elements. Used primarily for scrolling containers.
	ChildOffset Vector2
}

const sizeofClipElementConfig = 12

func encClipElementConfig(b []byte, p uint32, v *ClipElementConfig) {
	putBool(b, p+0, v.Horizontal)
	putBool(b, p+1, v.Vertical)
	encVector2(b, p+4, &v.ChildOffset)
}

func decClipElementConfig(m []byte, p uint32, v *ClipElementConfig) {
	v.Horizontal = getBool(m, p+0)
	v.Vertical = getBool(m, p+1)
	decVector2(m, p+4, &v.ChildOffset)
}

// Data representing the current internal state of a scrolling element.
type ScrollContainerData struct {
	// Note: This is a pointer to the real internal scroll position, mutating it may cause a change in final layout.
	// Intended for use with external functionality that modifies scroll position, such as scroll bars or auto scrolling.
	ScrollPosition Pointer[Vector2]
	// The bounding box of the scroll element.
	ScrollContainerDimensions Dimensions
	// The outer dimensions of the inner scroll container content, including the padding of the parent scroll container.
	ContentDimensions Dimensions
	// The config that was originally passed to the clip element.
	Config ClipElementConfig
	// Indicates whether an actual scroll container matched the provided ID or if the default struct was returned.
	Found bool
}

const sizeofScrollContainerData = 36

func decScrollContainerData(m []byte, p uint32, v *ScrollContainerData) {
	v.ScrollPosition = Pointer[Vector2]{addr: getU32(m, p+0)}
	decDimensions(m, p+4, &v.ScrollContainerDimensions)
	decDimensions(m, p+12, &v.ContentDimensions)
	decClipElementConfig(m, p+20, &v.Config)
	v.Found = getBool(m, p+32)
}

type TransitionData struct {
	BoundingBox     BoundingBox
	BackgroundColor Color
	OverlayColor    Color
	BorderColor     Color
	BorderWidth     BorderWidth
}

const sizeofTransitionData = 76

func encTransitionData(b []byte, p uint32, v *TransitionData) {
	encBoundingBox(b, p+0, &v.BoundingBox)
	encColor(b, p+16, &v.BackgroundColor)
	encColor(b, p+32, &v.OverlayColor)
	encColor(b, p+48, &v.BorderColor)
	encBorderWidth(b, p+64, &v.BorderWidth)
}

func decTransitionData(m []byte, p uint32, v *TransitionData) {
	decBoundingBox(m, p+0, &v.BoundingBox)
	decColor(m, p+16, &v.BackgroundColor)
	decColor(m, p+32, &v.OverlayColor)
	decColor(m, p+48, &v.BorderColor)
	decBorderWidth(m, p+64, &v.BorderWidth)
}

type TransitionCallbackArguments struct {
	TransitionState TransitionState
	Initial         TransitionData
	Current         Pointer[TransitionData]
	Target          TransitionData
	ElapsedTime     float32
	Duration        float32
	Properties      TransitionProperty
}

const sizeofTransitionCallbackArguments = 172

func decTransitionCallbackArguments(m []byte, p uint32, v *TransitionCallbackArguments) {
	v.TransitionState = TransitionState(getU32(m, p+0))
	decTransitionData(m, p+4, &v.Initial)
	v.Current = Pointer[TransitionData]{addr: getU32(m, p+80)}
	decTransitionData(m, p+84, &v.Target)
	v.ElapsedTime = getF32(m, p+160)
	v.Duration = getF32(m, p+164)
	v.Properties = TransitionProperty(getU32(m, p+168))
}

// Controls the minimum and maximum size in pixels that this element is allowed to grow or shrink to,
// overriding sizing types such as FIT or GROW.
type SizingMinMax struct {
	// The smallest final size of the element on this axis will be this value in pixels.
	Min float32
	// The largest final size of the element on this axis will be this value in pixels.
	Max float32
}

const sizeofSizingMinMax = 8

func encSizingMinMax(b []byte, p uint32, v *SizingMinMax) {
	putF32(b, p+0, v.Min)
	putF32(b, p+4, v.Max)
}

func decSizingMinMax(m []byte, p uint32, v *SizingMinMax) {
	v.Min = getF32(m, p+0)
	v.Max = getF32(m, p+4)
}

// Controls the sizing of this element along one axis inside its parent container.
type SizingAxis struct {
	Size struct {
		// union
		MinMax  SizingMinMax
		Percent float32
	}
	// Controls how the element takes up space inside its parent container.
	Type __SizingType
}

const sizeofSizingAxis = 12

func encSizingAxis(b []byte, p uint32, v *SizingAxis) {
	switch {
	case v.Size.MinMax != (SizingMinMax{}):
		encSizingMinMax(b, p+0+0, &v.Size.MinMax)
	case v.Size.Percent != 0:
		putF32(b, p+0+0, v.Size.Percent)
	}

	putU8(b, p+8, uint8(v.Type))
}

func decSizingAxis(m []byte, p uint32, v *SizingAxis) {
	decSizingMinMax(m, p+0+0, &v.Size.MinMax)
	v.Size.Percent = getF32(m, p+0+0)

	v.Type = __SizingType(getU8(m, p+8))
}

// Controls the sizing of this element along one axis inside its parent container.
type Sizing struct {
	// Controls the width sizing of the element, along the x axis.
	Width SizingAxis
	// Controls the height sizing of the element, along the y axis.
	Height SizingAxis
}

const sizeofSizing = 24

func encSizing(b []byte, p uint32, v *Sizing) {
	encSizingAxis(b, p+0, &v.Width)
	encSizingAxis(b, p+12, &v.Height)
}

func decSizing(m []byte, p uint32, v *Sizing) {
	decSizingAxis(m, p+0, &v.Width)
	decSizingAxis(m, p+12, &v.Height)
}

// Controls "padding" in pixels, which is a gap between the bounding box of this element and where its children
// will be placed.
type Padding struct {
	Left   uint16
	Right  uint16
	Top    uint16
	Bottom uint16
}

const sizeofPadding = 8

func encPadding(b []byte, p uint32, v *Padding) {
	putU16(b, p+0, uint16(v.Left))
	putU16(b, p+2, uint16(v.Right))
	putU16(b, p+4, uint16(v.Top))
	putU16(b, p+6, uint16(v.Bottom))
}

func decPadding(m []byte, p uint32, v *Padding) {
	v.Left = uint16(getU16(m, p+0))
	v.Right = uint16(getU16(m, p+2))
	v.Top = uint16(getU16(m, p+4))
	v.Bottom = uint16(getU16(m, p+6))
}

// Controls how child elements are aligned on each axis.
type ChildAlignment struct {
	// Controls alignment of children along the x axis.
	X LayoutAlignmentX
	// Controls alignment of children along the y axis.
	Y LayoutAlignmentY
}

const sizeofChildAlignment = 2

func encChildAlignment(b []byte, p uint32, v *ChildAlignment) {
	putU8(b, p+0, uint8(v.X))
	putU8(b, p+1, uint8(v.Y))
}

func decChildAlignment(m []byte, p uint32, v *ChildAlignment) {
	v.X = LayoutAlignmentX(getU8(m, p+0))
	v.Y = LayoutAlignmentY(getU8(m, p+1))
}

// Controls various settings that affect the size and position of an element, as well as the sizes and positions
// of any child elements.
type LayoutConfig struct {
	// Controls the sizing of this element inside it's parent container, including FIT, GROW, PERCENT and FIXED sizing.
	Sizing Sizing
	// Controls "padding" in pixels, which is a gap between the bounding box of this element and where its children will be placed.
	Padding Padding
	// Controls the gap in pixels between child elements along the layout axis (horizontal gap for LEFT_TO_RIGHT, vertical gap for TOP_TO_BOTTOM).
	ChildGap uint16
	// Controls how child elements are aligned on each axis.
	ChildAlignment ChildAlignment
	// Controls the direction in which child elements will be automatically laid out.
	LayoutDirection LayoutDirection
}

const sizeofLayoutConfig = 40

func encLayoutConfig(b []byte, p uint32, v *LayoutConfig) {
	encSizing(b, p+0, &v.Sizing)
	encPadding(b, p+24, &v.Padding)
	putU16(b, p+32, uint16(v.ChildGap))
	encChildAlignment(b, p+34, &v.ChildAlignment)
	putU8(b, p+36, uint8(v.LayoutDirection))
}

func decLayoutConfig(m []byte, p uint32, v *LayoutConfig) {
	decSizing(m, p+0, &v.Sizing)
	decPadding(m, p+24, &v.Padding)
	v.ChildGap = uint16(getU16(m, p+32))
	decChildAlignment(m, p+34, &v.ChildAlignment)
	v.LayoutDirection = LayoutDirection(getU8(m, p+36))
}

// Controls various settings related to aspect ratio scaling element.
type AspectRatioElementConfig struct {
	// A float representing the target "Aspect ratio" for an element, which is its final width divided by its final height.
	AspectRatio float32
}

const sizeofAspectRatioElementConfig = 4

func encAspectRatioElementConfig(b []byte, p uint32, v *AspectRatioElementConfig) {
	putF32(b, p+0, v.AspectRatio)
}

func decAspectRatioElementConfig(m []byte, p uint32, v *AspectRatioElementConfig) {
	v.AspectRatio = getF32(m, p+0)
}

// Controls various settings related to image elements.
type ImageElementConfig struct {
	// A transparent pointer used to pass image data through to the renderer.
	ImageData any
}

const sizeofImageElementConfig = 4

func encImageElementConfig(b []byte, p uint32, v *ImageElementConfig) {
	putU32(b, p+0, storeHandle(v.ImageData))
}

func decImageElementConfig(m []byte, p uint32, v *ImageElementConfig) {
	v.ImageData = loadHandle(getU32(m, p+0))
}

// Controls where a floating element is offset relative to its parent element.
type FloatingAttachPoints struct {
	// Controls the origin point on a floating element that attaches to its parent.
	Element FloatingAttachPointType
	// Controls the origin point on the parent element that the floating element attaches to.
	Parent FloatingAttachPointType
}

const sizeofFloatingAttachPoints = 2

func encFloatingAttachPoints(b []byte, p uint32, v *FloatingAttachPoints) {
	putU8(b, p+0, uint8(v.Element))
	putU8(b, p+1, uint8(v.Parent))
}

func decFloatingAttachPoints(m []byte, p uint32, v *FloatingAttachPoints) {
	v.Element = FloatingAttachPointType(getU8(m, p+0))
	v.Parent = FloatingAttachPointType(getU8(m, p+1))
}

// Controls various settings related to "floating" elements, which are elements that "float" above other elements, potentially overlapping their boundaries,
// and not affecting the layout of sibling or parent elements.
type FloatingElementConfig struct {
	// Offsets this floating element by the provided x,y coordinates from its attachPoints.
	Offset Vector2
	// Expands the boundaries of the outer floating element without affecting its children.
	Expand Dimensions
	// When used in conjunction with .attachTo = ATTACH_TO_ELEMENT_WITH_ID, attaches this floating element to the element in the hierarchy with the provided ID.
	// Hint: attach the ID to the other element with .id = CLAY_ID("yourId"), and specify the id the same way, with .parentId = CLAY_ID("yourId").id
	ParentId uint32
	// Controls the z index of this floating element and all its children. Floating elements are sorted in ascending z order before output.
	// zIndex is also passed to the renderer for all elements contained within this floating element.
	ZIndex int16
	// Controls how mouse pointer events like hover and click are captured or passed through to elements underneath / behind a floating element.
	// Enum is of the form CLAY_ATTACH_POINT_foo_bar. See FloatingAttachPoints for more details.
	// Note: see <img src="https://github.com/user-attachments/assets/b8c6dfaa-c1b1-41a4-be55-013473e4a6ce />
	// and <img src="https://github.com/user-attachments/assets/ebe75e0d-1904-46b0-982d-418f929d1516 /> for a visual explanation.
	AttachPoints FloatingAttachPoints
	// Controls how mouse pointer events like hover and click are captured or passed through to elements underneath a floating element.
	// POINTER_CAPTURE_MODE_CAPTURE (default) - "Capture" the pointer event and don't allow events like hover and click to pass through to elements underneath.
	// POINTER_CAPTURE_MODE_PASSTHROUGH - Transparently pass through pointer events like hover and click to elements underneath the floating element.
	PointerCaptureMode PointerCaptureMode
	// Controls which element a floating element is "attached" to (i.e. relative offset from).
	// ATTACH_TO_NONE (default) - Disables floating for this element.
	// ATTACH_TO_PARENT - Attaches this floating element to its parent, positioned based on the .attachPoints and .offset fields.
	// ATTACH_TO_ELEMENT_WITH_ID - Attaches this floating element to an element with a specific ID, specified with the .parentId field. positioned based on the .attachPoints and .offset fields.
	// ATTACH_TO_ROOT - Attaches this floating element to the root of the layout, which combined with the .offset field provides functionality similar to "absolute positioning".
	AttachTo FloatingAttachToElement
	// Controls whether or not a floating element is clipped to the same clipping rectangle as the element it's attached to.
	// CLIP_TO_NONE (default) - The floating element does not inherit clipping.
	// CLIP_TO_ATTACHED_PARENT - The floating element is clipped to the same clipping rectangle as the element it's attached to.
	ClipTo FloatingClipToElement
}

const sizeofFloatingElementConfig = 28

func encFloatingElementConfig(b []byte, p uint32, v *FloatingElementConfig) {
	encVector2(b, p+0, &v.Offset)
	encDimensions(b, p+8, &v.Expand)
	putU32(b, p+16, uint32(v.ParentId))
	putU16(b, p+20, uint16(v.ZIndex))
	encFloatingAttachPoints(b, p+22, &v.AttachPoints)
	putU8(b, p+24, uint8(v.PointerCaptureMode))
	putU8(b, p+25, uint8(v.AttachTo))
	putU8(b, p+26, uint8(v.ClipTo))
}

func decFloatingElementConfig(m []byte, p uint32, v *FloatingElementConfig) {
	decVector2(m, p+0, &v.Offset)
	decDimensions(m, p+8, &v.Expand)
	v.ParentId = uint32(getU32(m, p+16))
	v.ZIndex = int16(getU16(m, p+20))
	decFloatingAttachPoints(m, p+22, &v.AttachPoints)
	v.PointerCaptureMode = PointerCaptureMode(getU8(m, p+24))
	v.AttachTo = FloatingAttachToElement(getU8(m, p+25))
	v.ClipTo = FloatingClipToElement(getU8(m, p+26))
}

// Controls various settings related to custom elements.
type CustomElementConfig struct {
	// A transparent pointer through which you can pass custom data to the renderer.
	// Generates CUSTOM render commands.
	CustomData any
}

const sizeofCustomElementConfig = 4

func encCustomElementConfig(b []byte, p uint32, v *CustomElementConfig) {
	putU32(b, p+0, storeHandle(v.CustomData))
}

func decCustomElementConfig(m []byte, p uint32, v *CustomElementConfig) {
	v.CustomData = loadHandle(getU32(m, p+0))
}

// Controls settings related to element borders.
type BorderElementConfig struct {
	// Controls the color of all borders with width > 0. Conventionally represented as 0-255, but interpretation is up to the renderer.
	Color Color
	// Controls the widths of individual borders. At least one of these should be > 0 for a BORDER render command to be generated.
	Width BorderWidth
}

const sizeofBorderElementConfig = 28

func encBorderElementConfig(b []byte, p uint32, v *BorderElementConfig) {
	encColor(b, p+0, &v.Color)
	encBorderWidth(b, p+16, &v.Width)
}

func decBorderElementConfig(m []byte, p uint32, v *BorderElementConfig) {
	decColor(m, p+0, &v.Color)
	decBorderWidth(m, p+16, &v.Width)
}

// Controls settings related to transitions
type TransitionElementConfig struct {
	Duration            float32
	Properties          TransitionProperty
	InteractionHandling TransitionInteractionHandlingType
	Enter               struct {
		Trigger TransitionEnterTriggerType
	}
	Exit struct {
		Trigger         TransitionExitTriggerType
		SiblingOrdering ExitTransitionSiblingOrdering
	}
}

const sizeofTransitionElementConfig = 32

func encTransitionElementConfig(b []byte, p uint32, v *TransitionElementConfig) {
	putF32(b, p+4, v.Duration)
	putU32(b, p+8, uint32(v.Properties))
	putU8(b, p+12, uint8(v.InteractionHandling))
	putU8(b, p+16+4, uint8(v.Enter.Trigger))

	putU8(b, p+24+4, uint8(v.Exit.Trigger))
	putU8(b, p+24+5, uint8(v.Exit.SiblingOrdering))

}

func decTransitionElementConfig(m []byte, p uint32, v *TransitionElementConfig) {
	v.Duration = getF32(m, p+4)
	v.Properties = TransitionProperty(getU32(m, p+8))
	v.InteractionHandling = TransitionInteractionHandlingType(getU8(m, p+12))
	v.Enter.Trigger = TransitionEnterTriggerType(getU8(m, p+16+4))

	v.Exit.Trigger = TransitionExitTriggerType(getU8(m, p+24+4))
	v.Exit.SiblingOrdering = ExitTransitionSiblingOrdering(getU8(m, p+24+5))

}

type ElementDeclaration struct {
	// Controls various settings that affect the size and position of an element, as well as the sizes and positions of any child elements.
	Layout LayoutConfig
	// Controls the background color of the resulting element.
	// By convention specified as 0-255, but interpretation is up to the renderer.
	// If no other config is specified, .backgroundColor will generate a RECTANGLE render command, otherwise it will be passed as a property to IMAGE or CUSTOM render commands.
	BackgroundColor Color
	// Perform an image editing style "Color Overlay" on this element and all its children, equivalent to
	// glsl mix(elementColor, overlayColor.rgb, overlayColor.a)
	OverlayColor Color
	// Controls the "radius", or corner rounding of elements, including rectangles, borders and images.
	CornerRadius CornerRadius
	// Controls settings related to aspect ratio scaling.
	AspectRatio AspectRatioElementConfig
	// Controls settings related to image elements.
	Image ImageElementConfig
	// Controls whether and how an element "floats", which means it layers over the top of other elements in z order, and doesn't affect the position and size of siblings or parent elements.
	// Note: in order to activate floating, .floating.attachTo must be set to something other than the default value.
	Floating FloatingElementConfig
	// Used to create CUSTOM render commands, usually to render element types not supported by Clay.
	Custom CustomElementConfig
	// Controls whether an element should clip its contents, as well as providing child x,y offset configuration for scrolling.
	Clip ClipElementConfig
	// Controls settings related to element borders, and will generate BORDER render commands.
	Border     BorderElementConfig
	Transition TransitionElementConfig
	// A pointer that will be transparently passed through to resulting render commands.
	UserData any
}

const sizeofElementDeclaration = 204

func encElementDeclaration(b []byte, p uint32, v *ElementDeclaration) {
	encLayoutConfig(b, p+0, &v.Layout)
	encColor(b, p+40, &v.BackgroundColor)
	encColor(b, p+56, &v.OverlayColor)
	encCornerRadius(b, p+72, &v.CornerRadius)
	encAspectRatioElementConfig(b, p+88, &v.AspectRatio)
	encImageElementConfig(b, p+92, &v.Image)
	encFloatingElementConfig(b, p+96, &v.Floating)
	encCustomElementConfig(b, p+124, &v.Custom)
	encClipElementConfig(b, p+128, &v.Clip)
	encBorderElementConfig(b, p+140, &v.Border)
	encTransitionElementConfig(b, p+168, &v.Transition)
	putU32(b, p+200, storeHandle(v.UserData))
}

func decElementDeclaration(m []byte, p uint32, v *ElementDeclaration) {
	decLayoutConfig(m, p+0, &v.Layout)
	decColor(m, p+40, &v.BackgroundColor)
	decColor(m, p+56, &v.OverlayColor)
	decCornerRadius(m, p+72, &v.CornerRadius)
	decAspectRatioElementConfig(m, p+88, &v.AspectRatio)
	decImageElementConfig(m, p+92, &v.Image)
	decFloatingElementConfig(m, p+96, &v.Floating)
	decCustomElementConfig(m, p+124, &v.Custom)
	decClipElementConfig(m, p+128, &v.Clip)
	decBorderElementConfig(m, p+140, &v.Border)
	decTransitionElementConfig(m, p+168, &v.Transition)
	v.UserData = loadHandle(getU32(m, p+200))
}

// Controls various functionality related to text elements.
type TextElementConfig struct {
	// A pointer that will be transparently passed through to the resulting render command.
	UserData any
	// The RGBA color of the font to render, conventionally specified as 0-255.
	TextColor Color
	// An integer transparently passed to Clay_MeasureText to identify the font to use.
	// The debug view will pass fontId = 0 for its internal text.
	FontId uint16
	// Controls the size of the font. Handled by the function provided to Clay_MeasureText.
	FontSize uint16
	// Controls extra horizontal spacing between characters. Handled by the function provided to Clay_MeasureText.
	LetterSpacing uint16
	// Controls additional vertical space between wrapped lines of text.
	LineHeight uint16
	// Controls how text "wraps", that is how it is broken into multiple lines when there is insufficient horizontal space.
	// TEXT_WRAP_WORDS (default) breaks on whitespace characters.
	// TEXT_WRAP_NEWLINES doesn't break on space characters, only on newlines.
	// TEXT_WRAP_NONE disables wrapping entirely.
	WrapMode TextElementConfigWrapMode
	// Controls how wrapped lines of text are horizontally aligned within the outer text bounding box.
	// TEXT_ALIGN_LEFT (default) - Horizontally aligns wrapped lines of text to the left hand side of their bounding box.
	// TEXT_ALIGN_CENTER - Horizontally aligns wrapped lines of text to the center of their bounding box.
	// TEXT_ALIGN_RIGHT - Horizontally aligns wrapped lines of text to the right hand side of their bounding box.
	TextAlignment TextAlignment
}

const sizeofTextElementConfig = 32

func encTextElementConfig(b []byte, p uint32, v *TextElementConfig) {
	putU32(b, p+0, storeHandle(v.UserData))
	encColor(b, p+4, &v.TextColor)
	putU16(b, p+20, uint16(v.FontId))
	putU16(b, p+22, uint16(v.FontSize))
	putU16(b, p+24, uint16(v.LetterSpacing))
	putU16(b, p+26, uint16(v.LineHeight))
	putU8(b, p+28, uint8(v.WrapMode))
	putU8(b, p+29, uint8(v.TextAlignment))
}

func decTextElementConfig(m []byte, p uint32, v *TextElementConfig) {
	v.UserData = loadHandle(getU32(m, p+0))
	decColor(m, p+4, &v.TextColor)
	v.FontId = uint16(getU16(m, p+20))
	v.FontSize = uint16(getU16(m, p+22))
	v.LetterSpacing = uint16(getU16(m, p+24))
	v.LineHeight = uint16(getU16(m, p+26))
	v.WrapMode = TextElementConfigWrapMode(getU8(m, p+28))
	v.TextAlignment = TextAlignment(getU8(m, p+29))
}

// Data to identify the error that clay has encountered.
type ErrorData struct {
	// Represents the type of error clay encountered while computing layout.
	// ERROR_TYPE_TEXT_MEASUREMENT_FUNCTION_NOT_PROVIDED - A text measurement function wasn't provided using SetMeasureTextFunction(), or the provided function was null.
	// ERROR_TYPE_ARENA_CAPACITY_EXCEEDED - Clay attempted to allocate its internal data structures but ran out of space. The arena passed to Initialize was created with a capacity smaller than that required by MinMemorySize().
	// ERROR_TYPE_ELEMENTS_CAPACITY_EXCEEDED - Clay ran out of capacity in its internal array for storing elements. This limit can be increased with SetMaxElementCount().
	// ERROR_TYPE_TEXT_MEASUREMENT_CAPACITY_EXCEEDED - Clay ran out of capacity in its internal array for storing elements. This limit can be increased with SetMaxMeasureTextCacheWordCount().
	// ERROR_TYPE_DUPLICATE_ID - Two elements were declared with exactly the same ID within one layout.
	// ERROR_TYPE_FLOATING_CONTAINER_PARENT_NOT_FOUND - A floating element was declared using CLAY_ATTACH_TO_ELEMENT_ID and either an invalid .parentId was provided or no element with the provided .parentId was found.
	// ERROR_TYPE_PERCENTAGE_OVER_1 - An element was declared that using CLAY_SIZING_PERCENT but the percentage value was over 1. Percentage values are expected to be in the 0-1 range.
	// ERROR_TYPE_INTERNAL_ERROR - Clay encountered an internal error. It would be wonderful if you could report this so we can fix it!
	// ERROR_TYPE_UNBALANCED_OPEN_CLOSE - __OpenElement was called more times than __CloseElement, so there were still remaining open elements when the layout ended.
	// ERROR_TYPE_HASH_MAP_CAPACITY_EXCEEDED - Clay ran out of capacity in its internal hash map for storing element IDs -> elements. This limit can be increased with SetMaxElementCount().
	ErrorType ErrorType
	// A string containing human-readable error text that explains the error in more detail.
	ErrorText string
	// A transparent pointer passed through from when the error handler was first provided.
	UserData any
}

const sizeofErrorData = 20

func encErrorData(b []byte, p uint32, v *ErrorData) {
	putU8(b, p+0, uint8(v.ErrorType))
	encString(b, p+4, &v.ErrorText)
	putU32(b, p+16, storeHandle(v.UserData))
}

func decErrorData(m []byte, p uint32, v *ErrorData) {
	v.ErrorType = ErrorType(getU8(m, p+0))
	decString(m, p+4, &v.ErrorText)
	v.UserData = loadHandle(getU32(m, p+16))
}

// Returns the size, in bytes, of the minimum amount of memory Clay requires to operate at its current settings.
func MinMemorySize() uint32 {
	return uint32(module.Xgo_Clay_MinMemorySize())
}

// Sets the state of the "pointer" (i.e. the mouse or touch) in Clay's internal data. Used for detecting and responding to mouse events in the debug view,
// as well as for Hovered() and scroll element handling.
func SetPointerState(position Vector2, pointerDown bool) {
	argBuf := wasmArgs(8)
	encVector2(argBuf, 0, &position)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay_SetPointerState(int32(argPtr+0), b2i(pointerDown))
}

// Returns the state of the "pointer" (i.e. the mouse or touch) which was set via SetPointerState().
func GetPointerState() PointerData {
	argPtr := scratchAddr
	var ret PointerData
	module.Xgo_Clay_GetPointerState(int32(argPtr + 0))
	decPointerData(wasmMemory(), argPtr+0, &ret)
	return ret
}

// Returns the Context that clay is currently using. Used when using multiple instances of clay simultaneously.
func GetCurrentContext() *Context {
	return contextOf(uint32(module.Xgo_Clay_GetCurrentContext()))
}

// Sets the context that clay will use to compute the layout.
// Used to restore a context saved from GetCurrentContext when using multiple instances of clay simultaneously.
func SetCurrentContext(context *Context) {
	module.Xgo_Clay_SetCurrentContext(context.wasmAddr())
}

// Updates the state of Clay's internal scroll data, updating scroll content positions if scrollDelta is non zero, and progressing momentum scrolling.
//
//   - enableDragScrolling when set to true will enable mobile device like "touch drag" scroll of scroll containers, including momentum scrolling after the touch has ended.
//
//   - scrollDelta is the amount to scroll this frame on each axis in pixels.
//
//   - deltaTime is the time in seconds since the last "frame" (scroll update)
func UpdateScrollContainers(enableDragScrolling bool, scrollDelta Vector2, deltaTime float32) {
	argBuf := wasmArgs(8)
	encVector2(argBuf, 0, &scrollDelta)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay_UpdateScrollContainers(b2i(enableDragScrolling), int32(argPtr+0), float32(deltaTime))
}

// Returns the internally stored scroll offset for the currently open element.
// Generally intended for use with clip elements to create scrolling containers.
func GetScrollOffset() Vector2 {
	argPtr := scratchAddr
	var ret Vector2
	module.Xgo_Clay_GetScrollOffset(int32(argPtr + 0))
	decVector2(wasmMemory(), argPtr+0, &ret)
	return ret
}

// Updates the layout dimensions in response to the window or outer container being resized.
func SetLayoutDimensions(dimensions Dimensions) {
	argBuf := wasmArgs(8)
	encDimensions(argBuf, 0, &dimensions)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay_SetLayoutDimensions(int32(argPtr + 0))
}

// Returns the current dimensions set by SetLayoutDimensions.
func GetLayoutDimensions() Dimensions {
	argPtr := scratchAddr
	var ret Dimensions
	module.Xgo_Clay_GetLayoutDimensions(int32(argPtr + 0))
	decDimensions(wasmMemory(), argPtr+0, &ret)
	return ret
}

// Called before starting any layout declarations.
func beginLayout() {
	module.Xgo_Clay_BeginLayout()
}

var endLayoutResult RenderCommandArray

// Called when all layout declarations are finished.
// Computes the layout and generates and returns the array of render commands to draw.
// The returned slice is reused by the next call to EndLayout.
func EndLayout(deltaTime float32) RenderCommandArray {
	argPtr := scratchAddr
	module.Xgo_Clay_EndLayout(int32(argPtr+0), float32(deltaTime))
	decRenderCommandArray(wasmMemory(), argPtr+0, &endLayoutResult)
	return endLayoutResult
}

// Gets the ID of the currently open element, useful for retrieving IDs generated by CLAY_AUTO_ID()
func GetOpenElementId() uint32 {
	return uint32(module.Xgo_Clay_GetOpenElementId())
}

// Calculates a hash ID from the given idString.
// Generally only used for dynamic strings when CLAY_ID("stringLiteral") can't be used.
func GetElementId(idString string) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &idString)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay_GetElementId(int32(argPtr+16), int32(argPtr+0))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

// Calculates a hash ID from the given idString and index.
//
//   - index is used to avoid constructing dynamic ID strings in loops.
//
// Generally only used for dynamic strings when CLAY_IDI("stringLiteral", index) can't be used.
func GetElementIdWithIndex(idString string, index uint32) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &idString)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay_GetElementIdWithIndex(int32(argPtr+16), int32(argPtr+0), int32(index))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

// Returns layout data such as the final calculated bounding box for an element with a given ID.
// The returned ElementData contains a `found` bool that will be true if an element with the provided ID was found.
// This ID can be calculated either with CLAY_ID() for string literal IDs, or GetElementId for dynamic strings.
func GetElementData(id ElementId) ElementData {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &id)
	argPtr := wasmCommit(argBuf)
	var ret ElementData
	module.Xgo_Clay_GetElementData(int32(argPtr+24), int32(argPtr+0))
	decElementData(wasmMemory(), argPtr+24, &ret)
	return ret
}

// Returns true if the pointer position provided by SetPointerState is within the current element's bounding box.
// Works during element declaration, e.g. CLAY({ .backgroundColor = Hovered() ? BLUE : RED });
func Hovered() bool {
	return module.Xgo_Clay_Hovered() != 0
}

// An imperative function that returns true if the pointer position provided by SetPointerState is within the element with the provided ID's bounding box.
// This ID can be calculated either with CLAY_ID() for string literal IDs, or GetElementId for dynamic strings.
func PointerOver(elementId ElementId) bool {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &elementId)
	argPtr := wasmCommit(argBuf)
	return module.Xgo_Clay_PointerOver(int32(argPtr+0)) != 0
}

var getPointerOverIdsResult ElementIdArray

// Returns the array of element IDs that the pointer is currently over.
// The returned slice is reused by the next call to GetPointerOverIds.
func GetPointerOverIds() ElementIdArray {
	argPtr := scratchAddr
	module.Xgo_Clay_GetPointerOverIds(int32(argPtr + 0))
	decElementIdArray(wasmMemory(), argPtr+0, &getPointerOverIdsResult)
	return getPointerOverIdsResult
}

// Returns data representing the state of the scrolling element with the provided ID.
// The returned ScrollContainerData contains a `found` bool that will be true if a scroll element was found with the provided ID.
// An imperative function that returns true if the pointer position provided by SetPointerState is within the element with the provided ID's bounding box.
// This ID can be calculated either with CLAY_ID() for string literal IDs, or GetElementId for dynamic strings.
func GetScrollContainerData(id ElementId) ScrollContainerData {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &id)
	argPtr := wasmCommit(argBuf)
	var ret ScrollContainerData
	module.Xgo_Clay_GetScrollContainerData(int32(argPtr+24), int32(argPtr+0))
	decScrollContainerData(wasmMemory(), argPtr+24, &ret)
	return ret
}

// Enables and disables Clay's internal debug tools.
// This state is retained and does not need to be set each frame.
func SetDebugModeEnabled(enabled bool) {
	module.Xgo_Clay_SetDebugModeEnabled(b2i(enabled))
}

// Returns true if Clay's internal debug tools are currently enabled.
func IsDebugModeEnabled() bool {
	return module.Xgo_Clay_IsDebugModeEnabled() != 0
}

// Enables and disables visibility culling. By default, Clay will not generate render commands for elements whose bounding box is entirely outside the screen.
func SetCullingEnabled(enabled bool) {
	module.Xgo_Clay_SetCullingEnabled(b2i(enabled))
}

// Returns the maximum number of UI elements supported by Clay's current configuration.
func GetMaxElementCount() int32 {
	return int32(module.Xgo_Clay_GetMaxElementCount())
}

// Modifies the maximum number of UI elements supported by Clay's current configuration.
// This may require reallocating additional memory, and re-calling Initialize();
func SetMaxElementCount(maxElementCount int32) {
	module.Xgo_Clay_SetMaxElementCount(int32(maxElementCount))
}

// Returns the maximum number of measured "words" (whitespace seperated runs of characters) that Clay can store in its internal text measurement cache.
func GetMaxMeasureTextCacheWordCount() int32 {
	return int32(module.Xgo_Clay_GetMaxMeasureTextCacheWordCount())
}

// Modifies the maximum number of measured "words" (whitespace seperated runs of characters) that Clay can store in its internal text measurement cache.
// This may require reallocating additional memory, and re-calling Initialize();
func SetMaxMeasureTextCacheWordCount(maxMeasureTextCacheWordCount int32) {
	module.Xgo_Clay_SetMaxMeasureTextCacheWordCount(int32(maxMeasureTextCacheWordCount))
}

// Resets Clay's internal text measurement cache. Useful if font mappings have changed or fonts have been reloaded.
func ResetMeasureTextCache() {
	module.Xgo_Clay_ResetMeasureTextCache()
}

func __OpenElement() {
	module.Xgo_Clay__OpenElement()
}

func __OpenElementWithId(elementId ElementId) {
	argBuf := wasmArgs(24)
	encElementId(argBuf, 0, &elementId)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay__OpenElementWithId(int32(argPtr + 0))
}

func __ConfigureOpenElement(config ElementDeclaration) {
	argBuf := wasmArgs(204)
	encElementDeclaration(argBuf, 0, &config)
	argPtr := wasmCommit(argBuf)
	module.Xgo_Clay__ConfigureOpenElement(int32(argPtr + 0))
}

func __CloseElement() {
	module.Xgo_Clay__CloseElement()
}

func __HashString(key string, seed uint32) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &key)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay__HashString(int32(argPtr+16), int32(argPtr+0), int32(seed))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

func __HashStringWithOffset(key string, offset uint32, seed uint32) ElementId {
	argBuf := wasmArgs(12)
	encString(argBuf, 0, &key)
	argPtr := wasmCommit(argBuf)
	var ret ElementId
	module.Xgo_Clay__HashStringWithOffset(int32(argPtr+16), int32(argPtr+0), int32(offset), int32(seed))
	decElementId(wasmMemory(), argPtr+16, &ret)
	return ret
}

// PointerTarget is the set of types that a [Pointer] can point to.
type PointerTarget interface {
	TransitionData | Vector2
}

// maxPointerSize is the size of the largest type that a Pointer can point to.
const maxPointerSize = 76

func decodeValue(m []byte, p uint32, v any) {
	switch v := v.(type) {
	case *TransitionData:
		decTransitionData(m, p, v)
	case *Vector2:
		decVector2(m, p, v)
	default:
		panic("clay: unsupported pointer type")
	}
}

func encodeValue(b []byte, p uint32, v any) uint32 {
	switch v := v.(type) {
	case *TransitionData:
		encTransitionData(b, p, v)
		return sizeofTransitionData
	case *Vector2:
		encVector2(b, p, v)
		return sizeofVector2
	default:
		panic("clay: unsupported pointer type")
	}
}
