package main

import (
	"fmt"
	"go/format"
	"go/token"
	"log"
	"maps"
	"slices"
	"strings"
)

// renames gives functions that are wrapped by hand in the clay package a different Go name.
var renames = map[string]string{
	"Clay_BeginLayout": "beginLayout",
}

// handwritten lists functions that can't be generated and are implemented
// by hand using the exports of internal/wasm/clay.c.
var handwritten = map[string]bool{
	"Clay_CreateArenaWithCapacityAndMemory": true,
	"Clay_Initialize":                       true,
	"Clay_OnHover":                          true,
	"Clay_SetMeasureTextFunction":           true,
	"Clay_SetQueryScrollOffsetFunction":     true,
	"Clay__OpenTextElement":                 true,
	"Clay__StoreTextElementConfig":          true,
	"Clay__ConfigureOpenElementPtr":         true,
	// Not useful in Go.
	"Clay__SuppressUnusedLatchDefinitionVariableWarning": true,
	"Clay_RenderCommandArray_Get":                        true, // RenderCommandArray is a slice
}

// handwrittenTypes are types that can't be generated and are implemented by hand.
var handwrittenTypes = map[string]bool{
	"Clay_Arena":        true,
	"Clay_ErrorHandler": true,
}

// extraTypes are types used by the handwritten code that might not be reachable from generated functions.
var extraTypes = []string{
	"Clay_ErrorData",
	"Clay_StringSlice",
	"Clay_PointerData",
	"Clay_TextElementConfig",
	"Clay_ElementId",
	"Clay_Dimensions",
	"Clay_Vector2",
}

// unionTags describes how to find the active member of unions that can't be decoded
// all at once because they contain strings or user data.
// By default, a value like CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_START selects the member overlayColor.
var unionTags = map[string]unionTag{
	"Clay_RenderCommand.renderData": {
		tag:       "commandType",
		prefix:    "CLAY_RENDER_COMMAND_TYPE_",
		overrides: map[string]string{"SCISSOR": "clip"},
	},
}

type unionTag struct {
	tag       string
	prefix    string            // prefix of the enum constants
	overrides map[string]string // enum constant without prefix and _START/_END suffix -> union member
}

func (u unionTag) member(constant string) string {
	name := strings.TrimPrefix(constant, u.prefix)
	name = strings.TrimSuffix(strings.TrimSuffix(name, "_START"), "_END")
	if m, ok := u.overrides[name]; ok {
		return m
	}
	parts := strings.Split(strings.ToLower(name), "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = exportName(parts[i])
	}
	return strings.Join(parts, "")
}

// goFields returns the fields of r that are exposed in Go. Function pointers are left out,
// and are always NULL when a record is passed to clay.
func goFields(r *record) []*field {
	fields := make([]*field, 0, len(r.fields))
	for _, f := range r.fields {
		if f.t.kind != kFuncPtr {
			fields = append(fields, f)
		}
	}
	return fields
}

// minScratch is the minimum size of the scratch buffer used to pass arguments to wasm.
const minScratch = 4096

type gen struct {
	m        *model
	goOut    strings.Builder
	cOut     strings.Builder
	pointers []*record // targets of Pointer[T]
	scratch  uint32
}

type function struct {
	cName, goName string
	ret           *ctype
	params        []param
}

type param struct {
	cName, goName string
	t             *ctype
}

func generate(m *model) (goSrc, cSrc []byte, err error) {
	g := &gen{m: m, scratch: minScratch}
	var funcs []*function
	for _, n := range m.funcs {
		f, err := g.function(n)
		if err != nil {
			if !handwritten[n.Name] {
				log.Printf("skipping function %s: %v", n.Name, err)
			}
			continue
		}
		if handwritten[n.Name] {
			continue
		}
		funcs = append(funcs, f)
	}
	for _, name := range extraTypes {
		if _, err := m.resolve(name, nil, nil, ""); err != nil {
			return nil, nil, err
		}
	}
	for _, r := range m.recOrder {
		classify(r)
	}

	g.cOut.WriteString(cHeader)
	g.goOut.WriteString(goHeader)

	for _, e := range m.enumOrder {
		g.emitEnum(e)
	}
	for _, r := range m.recOrder {
		if err := g.emitRecord(r); err != nil && !handwrittenTypes[r.cName] {
			log.Printf("skipping type %s: %v", r.cName, err)
		}
	}
	for _, name := range slices.Sorted(maps.Keys(m.aliases)) {
		t := m.aliases[name]
		if t.kind == kRecord && t.rec.cName != name && strings.HasPrefix(name, "Clay_") && g.representable(t) {
			fmt.Fprintf(&g.goOut, "type %s = %s\n\n", goName(name), t.rec.goName)
		}
	}
	for _, f := range funcs {
		g.emitFunction(f)
	}
	g.emitPointers()

	fmt.Fprintf(&g.cOut, "static char go_scratch[%d] __attribute__((aligned(16)));\n\n", alignUp(g.scratch, 16))
	g.cOut.WriteString("GO_EXPORT(\"go_scratch\")\nvoid *go_scratch_addr(void) {\n\treturn go_scratch;\n}\n")

	goSrc, err = format.Source([]byte(g.goOut.String()))
	if err != nil {
		return []byte(g.goOut.String()), nil, err
	}
	return goSrc, []byte(g.cOut.String()), nil
}

const cHeader = `// Code generated by internal/cmd/generate; DO NOT EDIT.

#include <stddef.h>
#include "clay.h"

#define GO_EXPORT(name) __attribute__((export_name(name)))

`

const goHeader = `// Code generated by internal/cmd/generate from clay.h; DO NOT EDIT.

package clay

`

func (g *gen) function(n *node) (*function, error) {
	f := &function{cName: n.Name, goName: goName(n.Name)}
	if r, ok := renames[n.Name]; ok {
		f.goName = r
	}
	ret, err := g.m.resolve(returnType(n.Type.QualType), nil, nil, "")
	if err != nil {
		return nil, err
	}
	switch {
	case ret.kind == kVoid, ret.kind == kPrim, ret.kind == kEnum, isContext(ret):
	case ret.kind == kRecord && classify(ret.rec).dec:
	default:
		return nil, fmt.Errorf("unsupported return type %s", n.Type.QualType)
	}
	f.ret = ret
	for _, c := range n.Inner {
		if c.Kind != "ParmVarDecl" {
			continue
		}
		t, err := g.m.resolve(c.Type.QualType, nil, nil, "")
		if err != nil {
			return nil, err
		}
		switch {
		case t.kind == kPrim, t.kind == kEnum, isContext(t):
		case t.kind == kRecord && classify(t.rec).enc:
		default:
			return nil, fmt.Errorf("unsupported parameter %s of type %s", c.Name, c.Type.QualType)
		}
		name := c.Name
		if token.IsKeyword(name) || name == "" {
			name += "_"
		}
		f.params = append(f.params, param{cName: c.Name, goName: name, t: t})
	}
	return f, nil
}

// returnType extracts the return type from a function type like "int (char *, void (*)(int))".
func returnType(s string) string {
	depth := 0
	for i := len(s) - 1; i >= 0; i-- {
		switch s[i] {
		case ')':
			depth++
		case '(':
			depth--
			if depth == 0 {
				return strings.TrimSpace(s[:i])
			}
		}
	}
	return s
}

func isContext(t *ctype) bool {
	return t.kind == kPtr && t.elem.kind == kOpaque && strings.TrimPrefix(t.elem.cName, "struct ") == "Clay_Context"
}

func isVoidPtr(t *ctype) bool {
	return t.kind == kPtr && t.elem.kind == kVoid
}

// capabilities of a record.
type caps struct {
	done, enc, dec, plain bool
}

var recCaps = map[*record]*caps{}

func classify(r *record) caps {
	if c, ok := recCaps[r]; ok {
		return *c
	}
	c := &caps{done: true}
	recCaps[r] = c // break cycles

	if isStringRecord(r) {
		r.special = recString
		c.enc, c.dec = true, true
		return *c
	}
	if elem := arrayElem(r); elem != nil {
		r.special = recArray
		r.elem = elem
		c.dec = typeCaps(elem).dec
		return *c
	}
	c.enc, c.dec, c.plain = true, true, true
	for _, f := range goFields(r) {
		fc := typeCaps(f.t)
		c.plain = c.plain && fc.plain
		c.enc = c.enc && fc.enc
		if _, ok := unionTags[recordPath(r, f)]; ok {
			c.dec = c.dec && f.t.kind == kRecord && taggedUnionDecodable(f.t.rec)
		} else {
			c.dec = c.dec && fc.dec
		}
	}
	if r.union && !c.plain {
		// We can't know which member of the union is active.
		c.enc = false
		c.dec = false
	}
	return *c
}

func taggedUnionDecodable(r *record) bool {
	for _, f := range goFields(r) {
		if !typeCaps(f.t).dec {
			return false
		}
	}
	return true
}

func typeCaps(t *ctype) caps {
	switch t.kind {
	case kPrim, kEnum:
		return caps{enc: true, dec: true, plain: true}
	case kRecord:
		return classify(t.rec)
	case kArray:
		c := typeCaps(t.elem)
		c.enc = c.enc && c.plain
		c.dec = c.dec && c.plain
		return c
	case kPtr:
		if isVoidPtr(t) {
			return caps{enc: true, dec: true}
		}
		if t.elem.kind == kRecord && t.elem.rec.goName != "" && classify(t.elem.rec).plain {
			return caps{dec: true}
		}
	}
	return caps{}
}

func recordPath(r *record, f *field) string {
	if r.cName == "" {
		return r.owner.cName + "." + r.path + "." + f.cName
	}
	return r.cName + "." + f.cName
}

func isStringRecord(r *record) bool {
	var chars, length bool
	for _, f := range r.fields {
		switch {
		case f.cName == "chars" && f.t.kind == kPtr && f.t.elem.kind == kPrim && f.t.elem.prim.size == 1:
			chars = true
		case f.cName == "length" && f.t.kind == kPrim:
			length = true
		}
	}
	return chars && length && strings.HasPrefix(r.cName, "Clay_String")
}

func arrayElem(r *record) *ctype {
	if len(r.fields) != 3 || !strings.HasSuffix(r.cName, "Array") {
		return nil
	}
	if r.fields[0].cName != "capacity" || r.fields[1].cName != "length" || r.fields[2].cName != "internalArray" {
		return nil
	}
	if r.fields[2].t.kind != kPtr {
		return nil
	}
	return r.fields[2].t.elem
}

func (g *gen) representable(t *ctype) bool {
	_, ok := g.goType(t)
	return ok
}

func (g *gen) goType(t *ctype) (string, bool) {
	switch t.kind {
	case kPrim:
		return t.prim.goType, true
	case kEnum:
		return t.enum.goName, true
	case kArray:
		elem, ok := g.goType(t.elem)
		return fmt.Sprintf("[%d]%s", t.len, elem), ok
	case kPtr:
		if isVoidPtr(t) {
			return "any", true
		}
		if isContext(t) {
			return "*Context", true
		}
		if t.elem.kind == kRecord && t.elem.rec.goName != "" && classify(t.elem.rec).plain {
			if !slices.Contains(g.pointers, t.elem.rec) {
				g.pointers = append(g.pointers, t.elem.rec)
			}
			return "Pointer[" + t.elem.rec.goName + "]", true
		}
	case kRecord:
		r := t.rec
		classify(r)
		switch {
		case r.special == recString:
			return "string", true
		case r.goName != "":
			return r.goName, true
		}
		var b strings.Builder
		b.WriteString("struct {\n")
		if r.union {
			b.WriteString("// union\n")
		}
		for _, f := range goFields(r) {
			ft, ok := g.goType(f.t)
			if !ok {
				return "", false
			}
			fmt.Fprintf(&b, "%s %s\n", f.goName, ft)
		}
		b.WriteString("}")
		return b.String(), true
	}
	return "", false
}

func (g *gen) emitEnum(e *enum) {
	fmt.Fprintf(&g.goOut, "type %s %s\n\nconst (\n", e.goName, e.prim.goType)
	for _, c := range e.consts {
		fmt.Fprintf(&g.goOut, "%s %s = %d\n", c.goName, e.goName, c.value)
		fmt.Fprintf(&g.cOut, "_Static_assert(%s == %d, \"%s\");\n", c.cName, c.value, c.cName)
	}
	g.goOut.WriteString(")\n\n")
	fmt.Fprintf(&g.cOut, "_Static_assert(sizeof(%s) == %d, \"%s\");\n\n", e.cName, e.prim.size, e.cName)
}

func (g *gen) emitRecord(r *record) error {
	c := classify(r)
	if r.special == recString {
		return g.emitString(r)
	}

	g.emitLayoutAsserts(r, r.cName, "")

	if r.special == recArray {
		elem, ok := g.goType(r.elem)
		if !ok {
			return fmt.Errorf("unsupported element type")
		}
		esize, _ := r.elem.sizeAlign()
		fmt.Fprintf(&g.goOut, "type %s []%s\n\n", r.goName, elem)
		fmt.Fprintf(&g.goOut, "const sizeof%s = %d\n\n", r.goName, r.size)
		fmt.Fprintf(&g.goOut, "func dec%s(m []byte, p uint32, v *%s) {\n", r.goName, r.goName)
		fmt.Fprintf(&g.goOut, "n := int(int32(getU32(m, p+%d)))\naddr := getU32(m, p+%d)\n", r.fields[1].off, r.fields[2].off)
		fmt.Fprintf(&g.goOut, "s := (*v)[:0]\nif n <= 0 {\n*v = s\nreturn\n}\nif cap(s) < n {\ns = make(%s, n)\n}\ns = s[:n]\n", r.goName)
		fmt.Fprintf(&g.goOut, "for i := range s {\n%s\n}\n*v = s\n}\n\n", g.decExpr(r.elem, "addr+uint32(i)*"+fmt.Sprint(esize), "s[i]"))
		return nil
	}

	logOmittedFields(r, r.cName)
	var body strings.Builder
	for _, f := range goFields(r) {
		ft, ok := g.goType(f.t)
		if !ok {
			return fmt.Errorf("field %s has unsupported type", f.cName)
		}
		fmt.Fprintf(&body, "%s %s\n", f.goName, ft)
	}
	if r.union {
		fmt.Fprintf(&g.goOut, "type %s struct {\n// union\n%s}\n\n", r.goName, body.String())
	} else {
		fmt.Fprintf(&g.goOut, "type %s struct {\n%s}\n\n", r.goName, body.String())
	}
	fmt.Fprintf(&g.goOut, "const sizeof%s = %d\n\n", r.goName, r.size)

	if c.enc {
		fmt.Fprintf(&g.goOut, "func enc%s(b []byte, p uint32, v *%s) {\n", r.goName, r.goName)
		g.goOut.WriteString(g.encFields(r, "p", "v"))
		g.goOut.WriteString("}\n\n")
	}
	if c.dec {
		fmt.Fprintf(&g.goOut, "func dec%s(m []byte, p uint32, v *%s) {\n", r.goName, r.goName)
		g.goOut.WriteString(g.decFields(r, "p", "v"))
		g.goOut.WriteString("}\n\n")
	}
	return nil
}

func logOmittedFields(r *record, path string) {
	for _, f := range r.fields {
		switch {
		case f.t.kind == kFuncPtr:
			log.Printf("function pointer %s.%s is not available in Go", path, f.cName)
		case f.t.kind == kRecord && f.t.rec.goName == "":
			logOmittedFields(f.t.rec, path+"."+f.cName)
		}
	}
}

func (g *gen) emitLayoutAsserts(r *record, cName, path string) {
	if path == "" {
		fmt.Fprintf(&g.cOut, "_Static_assert(sizeof(%s) == %d, \"%s\");\n", cName, r.size, cName)
	}
	for _, f := range r.fields {
		fpath := path + f.cName
		// offsetof is relative to the named record, so add the offsets of the anonymous parents.
		fmt.Fprintf(&g.cOut, "_Static_assert(offsetof(%s, %s) == %s, \"%s.%s\");\n", cName, fpath, g.absOffset(r, f), cName, fpath)
		if f.t.kind == kRecord && f.t.rec.goName == "" {
			g.emitLayoutAsserts(f.t.rec, cName, fpath+".")
		}
	}
	if path == "" {
		g.cOut.WriteString("\n")
	}
}

func (g *gen) absOffset(r *record, f *field) string {
	off := f.off
	for cur := r; cur.cName == "" && cur.owner != nil; {
		// find the field in the owner chain holding cur
		parent, pf := findHolder(cur.owner, cur)
		if pf == nil {
			break
		}
		off += pf.off
		cur = parent
	}
	return fmt.Sprint(off)
}

func findHolder(r *record, target *record) (*record, *field) {
	for _, f := range r.fields {
		if f.t.kind != kRecord || f.t.rec.goName != "" {
			continue
		}
		if f.t.rec == target {
			return r, f
		}
		if h, hf := findHolder(f.t.rec, target); hf != nil {
			return h, hf
		}
	}
	return nil, nil
}

func (g *gen) emitString(r *record) error {
	var chars, length *field
	var others []*field
	for _, f := range r.fields {
		switch {
		case f.cName == "chars":
			chars = f
		case f.cName == "length":
			length = f
		default:
			others = append(others, f)
		}
	}
	g.emitLayoutAsserts(r, r.cName, "")
	fmt.Fprintf(&g.goOut, "const sizeof%s = %d\n\n", r.goName, r.size)
	fmt.Fprintf(&g.goOut, "func enc%s(b []byte, p uint32, v *string) {\n", r.goName)
	fmt.Fprintf(&g.goOut, "addr := storeString(*v)\nputU32(b, p+%d, addr)\nputU32(b, p+%d, uint32(len(*v)))\n", chars.off, length.off)
	for _, f := range others {
		// Slices derived from Go strings have themselves as their base.
		if f.t.kind == kPtr {
			fmt.Fprintf(&g.goOut, "putU32(b, p+%d, addr)\n", f.off)
		}
	}
	g.goOut.WriteString("}\n\n")
	fmt.Fprintf(&g.goOut, "func dec%s(m []byte, p uint32, v *string) {\n", r.goName)
	fmt.Fprintf(&g.goOut, "*v = loadString(m, getU32(m, p+%d), getU32(m, p+%d))\n}\n\n", chars.off, length.off)
	return nil
}

func primSuffix(p *prim) string {
	switch p.goType {
	case "bool":
		return "Bool"
	case "float32":
		return "F32"
	case "float64":
		return "F64"
	}
	return fmt.Sprintf("U%d", p.size*8)
}

func (g *gen) encFields(r *record, p, v string) string {
	var b strings.Builder
	if r.union {
		b.WriteString("switch {\n")
		for _, f := range goFields(r) {
			ft, _ := g.goType(f.t)
			zero := "0"
			switch {
			case f.t.kind == kRecord || f.t.kind == kArray:
				zero = "(" + ft + "{})"
			case f.t.kind == kPrim && f.t.prim.goType == "bool":
				zero = "false"
			}
			fmt.Fprintf(&b, "case %s.%s != %s:\n%s\n", v, f.goName, zero, g.encExpr(f.t, fmt.Sprintf("%s+%d", p, f.off), v+"."+f.goName))
		}
		b.WriteString("}\n")
		return b.String()
	}
	for _, f := range goFields(r) {
		fmt.Fprintf(&b, "%s\n", g.encExpr(f.t, fmt.Sprintf("%s+%d", p, f.off), v+"."+f.goName))
	}
	return b.String()
}

func (g *gen) encExpr(t *ctype, off, lv string) string {
	switch t.kind {
	case kPrim:
		if t.prim.goType == "bool" || strings.HasPrefix(t.prim.goType, "float") {
			return fmt.Sprintf("put%s(b, %s, %s)", primSuffix(t.prim), off, lv)
		}
		return fmt.Sprintf("put%s(b, %s, uint%d(%s))", primSuffix(t.prim), off, t.prim.size*8, lv)
	case kEnum:
		return fmt.Sprintf("put%s(b, %s, uint%d(%s))", primSuffix(t.enum.prim), off, t.enum.prim.size*8, lv)
	case kPtr: // void *
		return fmt.Sprintf("putU32(b, %s, storeHandle(%s))", off, lv)
	case kArray:
		size, _ := t.elem.sizeAlign()
		return fmt.Sprintf("for i := range %s {\n%s\n}", lv, g.encExpr(t.elem, fmt.Sprintf("%s+uint32(i)*%d", off, size), lv+"[i]"))
	case kRecord:
		if t.rec.goName != "" {
			return fmt.Sprintf("enc%s(b, %s, &%s)", t.rec.goName, off, lv)
		}
		return g.encFields(t.rec, off, lv)
	}
	panic("unreachable")
}

func (g *gen) decFields(r *record, p, v string) string {
	var b, tagged strings.Builder
	for _, f := range goFields(r) {
		off := fmt.Sprintf("%s+%d", p, f.off)
		tag, ok := unionTags[recordPath(r, f)]
		if !ok {
			fmt.Fprintf(&b, "%s\n", g.decExpr(f.t, off, v+"."+f.goName))
			continue
		}
		var tagField *field
		for _, tf := range r.fields {
			if tf.cName == tag.tag {
				tagField = tf
			}
		}
		if tagField == nil || tagField.t.kind != kEnum {
			log.Fatalf("union %s: tag field %s is not an enum", recordPath(r, f), tag.tag)
		}
		ft, _ := g.goType(f.t)
		fmt.Fprintf(&tagged, "%s.%s = %s{}\nswitch %s.%s {\n", v, f.goName, ft, v, tagField.goName)
		used := map[string]bool{}
		for _, c := range tagField.t.enum.consts {
			member := tag.member(c.cName)
			var mf *field
			for _, uf := range goFields(f.t.rec) {
				if uf.cName == member {
					mf = uf
				}
			}
			if mf == nil {
				continue
			}
			used[member] = true
			fmt.Fprintf(&tagged, "case %s:\n%s\n", c.goName, g.decExpr(mf.t, fmt.Sprintf("%s+%d", off, mf.off), v+"."+f.goName+"."+mf.goName))
		}
		for _, uf := range goFields(f.t.rec) {
			if !used[uf.cName] && !typeCaps(uf.t).plain {
				log.Fatalf("union %s: member %s is not associated with a value of %s", recordPath(r, f), uf.cName, tag.tag)
			}
		}
		tagged.WriteString("}\n")
	}
	b.WriteString(tagged.String())
	return b.String()
}

func (g *gen) decExpr(t *ctype, off, lv string) string {
	switch t.kind {
	case kPrim:
		switch t.prim.goType {
		case "bool", "float32", "float64":
			return fmt.Sprintf("%s = get%s(m, %s)", lv, primSuffix(t.prim), off)
		}
		return fmt.Sprintf("%s = %s(get%s(m, %s))", lv, t.prim.goType, primSuffix(t.prim), off)
	case kEnum:
		return fmt.Sprintf("%s = %s(get%s(m, %s))", lv, t.enum.goName, primSuffix(t.enum.prim), off)
	case kPtr:
		if isVoidPtr(t) {
			return fmt.Sprintf("%s = loadHandle(getU32(m, %s))", lv, off)
		}
		return fmt.Sprintf("%s = Pointer[%s]{addr: getU32(m, %s)}", lv, t.elem.rec.goName, off)
	case kArray:
		size, _ := t.elem.sizeAlign()
		return fmt.Sprintf("for i := range %s {\n%s\n}", lv, g.decExpr(t.elem, fmt.Sprintf("%s+uint32(i)*%d", off, size), lv+"[i]"))
	case kRecord:
		if t.rec.goName != "" {
			return fmt.Sprintf("dec%s(m, %s, &%s)", t.rec.goName, off, lv)
		}
		return g.decFields(t.rec, off, lv)
	}
	panic("unreachable")
}

func wasmType(t *ctype) string {
	switch t.kind {
	case kPrim:
		switch t.prim.wasm {
		case "i64":
			return "int64"
		case "f32":
			return "float32"
		case "f64":
			return "float64"
		}
	}
	return "int32"
}

func (g *gen) emitFunction(f *function) {
	export := "go_" + f.cName

	// Lay out the struct arguments and the result in the scratch buffer.
	var off uint32
	offsets := make([]uint32, len(f.params))
	for i, p := range f.params {
		if p.t.kind == kRecord {
			size, _ := p.t.sizeAlign()
			off = alignUp(off, 8)
			offsets[i] = off
			off += size
		}
	}
	argSize := off
	retOff := alignUp(off, 8)
	if f.ret.kind == kRecord {
		size, _ := f.ret.sizeAlign()
		off = retOff + size
	}
	g.scratch = max(g.scratch, off)

	// C wrapper
	var cParams, cArgs, cCopies []string
	if f.ret.kind == kRecord {
		cParams = append(cParams, f.ret.cName+" *ret")
	}
	for i, p := range f.params {
		if p.t.kind == kRecord {
			cParams = append(cParams, fmt.Sprintf("%s *p%d", p.t.cName, i))
			cCopies = append(cCopies, fmt.Sprintf("\t%s a%d = *p%d;\n", p.t.cName, i, i))
			cArgs = append(cArgs, fmt.Sprintf("a%d", i))
		} else {
			cParams = append(cParams, fmt.Sprintf("%s p%d", g.cScalar(p.t), i))
			cArgs = append(cArgs, fmt.Sprintf("p%d", i))
		}
	}
	cRet := "void"
	if f.ret.kind != kRecord {
		cRet = g.cScalar(f.ret)
	}
	if len(cParams) == 0 {
		cParams = []string{"void"}
	}
	fmt.Fprintf(&g.cOut, "GO_EXPORT(%q)\n%s %s(%s) {\n%s", export, cRet, export, strings.Join(cParams, ", "), strings.Join(cCopies, ""))
	call := fmt.Sprintf("%s(%s)", f.cName, strings.Join(cArgs, ", "))
	switch f.ret.kind {
	case kVoid:
		fmt.Fprintf(&g.cOut, "\t%s;\n}\n\n", call)
	case kRecord:
		fmt.Fprintf(&g.cOut, "\t%s r = %s;\n\t*ret = r;\n}\n\n", f.ret.cName, call)
	default:
		fmt.Fprintf(&g.cOut, "\treturn %s;\n}\n\n", call)
	}

	// Go wrapper
	var goParams, goArgs []string
	var body strings.Builder
	hasStructs := argSize > 0
	if hasStructs {
		fmt.Fprintf(&body, "argBuf := wasmArgs(%d)\n", argSize)
	}
	if f.ret.kind == kRecord {
		goArgs = append(goArgs, fmt.Sprintf("int32(argPtr+%d)", retOff))
	}
	for i, p := range f.params {
		gt, _ := g.goType(p.t)
		goParams = append(goParams, p.goName+" "+gt)
		switch {
		case p.t.kind == kRecord:
			fmt.Fprintf(&body, "%s\n", strings.ReplaceAll(g.encExpr(p.t, fmt.Sprint(offsets[i]), p.goName), "(b,", "(argBuf,"))
			goArgs = append(goArgs, fmt.Sprintf("int32(argPtr+%d)", offsets[i]))
		case isContext(p.t):
			goArgs = append(goArgs, p.goName+".wasmAddr()")
		case p.t.kind == kPrim && p.t.prim.goType == "bool":
			goArgs = append(goArgs, "b2i("+p.goName+")")
		default:
			goArgs = append(goArgs, fmt.Sprintf("%s(%s)", wasmType(p.t), p.goName))
		}
	}
	if hasStructs {
		body.WriteString("argPtr := wasmCommit(argBuf)\n")
	} else if f.ret.kind == kRecord {
		body.WriteString("argPtr := scratchAddr\n")
	}
	call = fmt.Sprintf("module.X%s(%s)", export, strings.Join(goArgs, ", "))
	goRet, doc := "", ""
	switch f.ret.kind {
	case kVoid:
		fmt.Fprintf(&body, "%s\n", call)
	case kRecord:
		goRet, _ = g.goType(f.ret)
		ret := "ret"
		if f.ret.rec.special == recArray {
			// Reuse the slice across calls, like clay reuses its internal array.
			ret = strings.ToLower(f.goName[:1]) + f.goName[1:] + "Result"
			doc = fmt.Sprintf("// The returned slice is reused by the next call to %s.\n", f.goName)
			fmt.Fprintf(&g.goOut, "var %s %s\n\n", ret, goRet)
		} else {
			fmt.Fprintf(&body, "var ret %s\n", goRet)
		}
		fmt.Fprintf(&body, "%s\n%s\nreturn %s\n", call, strings.ReplaceAll(g.decExpr(f.ret, fmt.Sprintf("argPtr+%d", retOff), ret), "(m,", "(wasmMemory(),"), ret)
	default:
		goRet, _ = g.goType(f.ret)
		switch {
		case isContext(f.ret):
			fmt.Fprintf(&body, "return contextOf(uint32(%s))\n", call)
		case f.ret.kind == kPrim && f.ret.prim.goType == "bool":
			fmt.Fprintf(&body, "return %s != 0\n", call)
		default:
			fmt.Fprintf(&body, "return %s(%s)\n", goRet, call)
		}
	}
	fmt.Fprintf(&g.goOut, "%sfunc %s(%s) %s {\n%s}\n\n", doc, f.goName, strings.Join(goParams, ", "), goRet, body.String())
}

func (g *gen) cScalar(t *ctype) string {
	switch t.kind {
	case kVoid:
		return "void"
	case kPrim:
		for _, name := range []string{"bool", "int8_t", "uint8_t", "int16_t", "uint16_t", "int32_t", "uint32_t", "int64_t", "uint64_t", "float", "double"} {
			if prims[name].goType == t.prim.goType {
				return name
			}
		}
	case kEnum:
		return t.enum.cName
	case kPtr:
		if isContext(t) {
			return "Clay_Context *"
		}
	}
	panic("unsupported scalar type")
}

func (g *gen) emitPointers() {
	g.goOut.WriteString("func decodeValue(m []byte, p uint32, v any) {\nswitch v := v.(type) {\n")
	for _, r := range g.pointers {
		fmt.Fprintf(&g.goOut, "case *%s:\ndec%s(m, p, v)\n", r.goName, r.goName)
	}
	g.goOut.WriteString("default:\npanic(\"clay: unsupported pointer type\")\n}\n}\n\n")
	g.goOut.WriteString("func encodeValue(b []byte, p uint32, v any) uint32 {\nswitch v := v.(type) {\n")
	for _, r := range g.pointers {
		fmt.Fprintf(&g.goOut, "case *%s:\nenc%s(b, p, v)\nreturn sizeof%s\n", r.goName, r.goName, r.goName)
	}
	g.goOut.WriteString("default:\npanic(\"clay: unsupported pointer type\")\n}\n}\n\n")
}
